"""Shared Multiprovider v2 candidate/generation contracts.

MP-0B adds the provider-neutral candidate kernel. MP-0C extends the same
foundation with artifact/dependency contracts and deterministic equivalence,
and MP-0D adds provider runtime governance/provenance/observability contracts without model execution; UI remains later scope.
"""

from .compatibility import wrap_technical_design_candidate
from .product_definition import DeterministicProductDefinitionProvider, artifact_type_for_stage
from .dependencies import (
    ArtifactAuthorityRecord,
    ArtifactDependencyProfile,
    ArtifactDependencyResolutionError,
    ArtifactDependencyResolver,
    DependencyRequirement,
    ResolvedArtifactContext,
    load_product_definition_dependency_profiles,
    select_product_definition_dependency_profile,
)
from .runtime import (
    FallbackDecision,
    GenerationProvenanceEnvelope,
    GenerationProviderRegistryView,
    GenerationRoute,
    GenerationRouteResolver,
    ProviderAvailability,
    ProviderExecutionReceipt,
    ProviderHealthSnapshot,
    ProviderSelectionPolicy,
    build_execution_receipt,
    build_provenance,
    prompt_reference_snapshot,
    provider_authority_surface,
    provider_runtime_span,
)
from .equivalence import (
    DeterministicEquivalenceHarness,
    EquivalenceContract,
    EquivalenceMode,
    EquivalenceResult,
)
from .contracts import (
    ArtifactCandidateEnvelope,
    CandidateComparisonGroup,
    CandidateLineage,
    CandidateOrigin,
    CandidateOriginKind,
    CandidateReference,
    CandidateStatus,
    DownstreamAuthorityBinding,
    GenerationProvider,
    GenerationProvenance,
    GenerationRequest,
    LEGAL_TRANSITIONS,
    LineageReason,
    ProviderClass,
    canonical_sha256,
    create_candidate,
    create_successor_candidate,
    invalidate_stale_authority,
    provider_authority_violations,
    transition_candidate,
)

__all__ = [
    "ArtifactCandidateEnvelope",
    "ArtifactAuthorityRecord",
    "ArtifactDependencyProfile",
    "ArtifactDependencyResolutionError",
    "ArtifactDependencyResolver",
    "DependencyRequirement",
    "ResolvedArtifactContext",
    "load_product_definition_dependency_profiles",
    "select_product_definition_dependency_profile",
    "DeterministicEquivalenceHarness",
    "EquivalenceContract",
    "EquivalenceMode",
    "EquivalenceResult",
    "CandidateComparisonGroup",
    "CandidateLineage",
    "CandidateOrigin",
    "CandidateOriginKind",
    "CandidateReference",
    "CandidateStatus",
    "DownstreamAuthorityBinding",
    "GenerationProvider",
    "GenerationProvenance",
    "GenerationRequest",
    "LEGAL_TRANSITIONS",
    "LineageReason",
    "ProviderClass",
    "canonical_sha256",
    "create_candidate",
    "create_successor_candidate",
    "invalidate_stale_authority",
    "provider_authority_violations",
    "transition_candidate",
    "FallbackDecision",
    "GenerationProvenanceEnvelope",
    "GenerationProviderRegistryView",
    "GenerationRoute",
    "GenerationRouteResolver",
    "ProviderAvailability",
    "ProviderExecutionReceipt",
    "ProviderHealthSnapshot",
    "ProviderSelectionPolicy",
    "build_execution_receipt",
    "build_provenance",
    "prompt_reference_snapshot",
    "provider_authority_surface",
    "provider_runtime_span",
    "wrap_technical_design_candidate",
    "DeterministicProductDefinitionProvider",
    "artifact_type_for_stage",
]
