from __future__ import annotations

from dataclasses import dataclass

from devpilot_core.policy.decisions import PolicyDecision, PolicyEffect


@dataclass(frozen=True)
class CostPolicy:
    """Local deterministic budget policy for external model/API usage."""

    external_api_allowed: bool = False
    budget_limit_usd: float = 0.0
    budget_used_usd: float = 0.0
    allowed_providers: tuple[str, ...] = ("mock", "local", "ollama", "lmstudio")


def load_cost_policy(root, *, policy_path: str = ".devpilot/policy.yaml") -> CostPolicy:
    """Load the minimal local cost policy from `.devpilot/policy.yaml`.

    This parser is intentionally narrow and dependency-free. It supports only
    the deterministic policy shape generated by FUNC-SPRINT-09. Missing files
    or malformed values fail closed to the default policy.
    """

    from pathlib import Path

    path = Path(root) / policy_path
    if not path.is_file():
        return CostPolicy()
    values = {
        "external_api_allowed": False,
        "budget_limit_usd": 0.0,
        "budget_used_usd": 0.0,
        "allowed_providers": [],
    }
    current_section: str | None = None
    current_key: str | None = None
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.rstrip()
        if not line or line.lstrip().startswith("#"):
            continue
        stripped = line.strip()
        if not line.startswith(" ") and stripped.endswith(":"):
            current_section = stripped[:-1]
            current_key = None
            continue
        if current_section == "cost" and stripped.startswith("-") and current_key == "allowed_providers":
            values["allowed_providers"].append(stripped[1:].strip().strip('"'))
            continue
        if current_section == "cost" and line.startswith("  ") and ":" in stripped:
            key, raw_value = stripped.split(":", 1)
            key = key.strip()
            raw_value = raw_value.strip()
            current_key = key
            if key == "allowed_providers":
                continue
            if key == "external_api_allowed":
                values[key] = raw_value.lower() == "true"
            elif key in {"budget_limit_usd", "budget_used_usd"}:
                try:
                    values[key] = float(raw_value)
                except ValueError:
                    values[key] = 0.0
    allowed = tuple(values["allowed_providers"] or ["mock", "local", "ollama", "lmstudio"])
    return CostPolicy(
        external_api_allowed=bool(values["external_api_allowed"]),
        budget_limit_usd=float(values["budget_limit_usd"]),
        budget_used_usd=float(values["budget_used_usd"]),
        allowed_providers=allowed,
    )


class CostGuard:
    """Guard that blocks external-cost actions unless explicitly budgeted.

    FUNC-SPRINT-09 keeps CostGuard offline and deterministic. It does not query
    providers or track real invoices. It evaluates requested usage against a
    local policy object so future ModelAdapter and API integrations cannot be
    enabled without an explicit budget gate.
    """

    def __init__(self, policy: CostPolicy | None = None) -> None:
        self.policy = policy or CostPolicy()

    def evaluate(
        self,
        *,
        external_api: bool = False,
        provider: str | None = None,
        estimated_cost_usd: float = 0.0,
    ) -> PolicyDecision:
        provider_normalized = (provider or "local").strip().lower()
        metadata = {
            "external_api": external_api,
            "provider": provider_normalized,
            "estimated_cost_usd": estimated_cost_usd,
            "budget_limit_usd": self.policy.budget_limit_usd,
            "budget_used_usd": self.policy.budget_used_usd,
        }

        if not external_api and provider_normalized in self.policy.allowed_providers and estimated_cost_usd <= 0:
            return PolicyDecision(
                effect=PolicyEffect.ALLOW,
                reason="CostGuard allowed local/mock/no-cost execution.",
                guard="CostGuard",
                rule_id="COSTGUARD_LOCAL_ALLOWED",
                metadata=metadata,
            )

        if external_api and not self.policy.external_api_allowed:
            return PolicyDecision(
                effect=PolicyEffect.BLOCK,
                reason="CostGuard blocked external API usage because no explicit local budget policy allows it.",
                guard="CostGuard",
                rule_id="COSTGUARD_EXTERNAL_API_BLOCKED",
                metadata=metadata,
            )

        projected = self.policy.budget_used_usd + max(estimated_cost_usd, 0.0)
        if projected > self.policy.budget_limit_usd:
            return PolicyDecision(
                effect=PolicyEffect.BLOCK,
                reason="CostGuard blocked execution because estimated cost exceeds the local budget limit.",
                guard="CostGuard",
                rule_id="COSTGUARD_BUDGET_EXCEEDED",
                metadata={**metadata, "projected_cost_usd": projected},
            )

        if estimated_cost_usd > 0:
            return PolicyDecision(
                effect=PolicyEffect.WARN,
                reason="CostGuard allowed budgeted execution with a cost warning.",
                guard="CostGuard",
                rule_id="COSTGUARD_BUDGETED_WARNING",
                metadata={**metadata, "projected_cost_usd": projected},
            )

        return PolicyDecision(
            effect=PolicyEffect.ALLOW,
            reason="CostGuard allowed execution under current local policy.",
            guard="CostGuard",
            rule_id="COSTGUARD_PASS",
            metadata=metadata,
        )
