from __future__ import annotations

import json
import re
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

from devpilot_core.cli_models import CommandResult
from devpilot_core.reports.models import EvidenceReport

_SAFE_FILENAME_PATTERN = re.compile(r"[^a-zA-Z0-9_.-]+")


@dataclass(frozen=True)
class WrittenReportPaths:
    """Root-relative paths generated by the ReportEngine."""

    json: str
    markdown: str

    def to_dict(self) -> dict[str, str]:
        return {"json": self.json, "markdown": self.markdown}


class ReportEngine:
    """Central JSON/Markdown evidence writer for DevPilot commands.

    FUNC-SPRINT-06 introduces this class to avoid command-specific report
    writers. The engine does not call external services, does not require API
    keys and only writes below `outputs/reports` by default.
    """

    def __init__(self, root: Path, *, reports_dir: str | Path = "outputs/reports") -> None:
        self.root = root
        self.reports_dir = self._resolve_reports_dir(reports_dir)

    def write_command_report(
        self,
        result: CommandResult,
        *,
        report_id: str | None = None,
        subject: str | Path | None = None,
        generated_at: datetime | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> WrittenReportPaths:
        """Persist one command result as JSON and Markdown evidence."""

        effective_report_id = report_id or build_report_id(result.command, subject=subject)
        report = EvidenceReport.from_command_result(
            result,
            report_id=effective_report_id,
            generated_at=generated_at,
            subject=_display_subject(subject, self.root),
            project_root=".",
            metadata=metadata,
        )
        return self.write_report(report)

    def write_report(self, report: EvidenceReport) -> WrittenReportPaths:
        """Write a previously built report in both supported formats."""

        self.reports_dir.mkdir(parents=True, exist_ok=True)
        base_name = sanitize_report_id(report.report_id)
        json_path = self.reports_dir / f"{base_name}.json"
        markdown_path = self.reports_dir / f"{base_name}.md"

        paths = WrittenReportPaths(json=_relative(json_path, self.root), markdown=_relative(markdown_path, self.root))
        payload = report.to_dict()
        payload["output_paths"] = paths.to_dict()

        json_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
        markdown_path.write_text(render_markdown_report(report, output_paths=paths.to_dict()), encoding="utf-8")
        return paths

    def _resolve_reports_dir(self, reports_dir: str | Path) -> Path:
        candidate = Path(reports_dir)
        if not candidate.is_absolute():
            candidate = self.root / candidate
        candidate = candidate.resolve()
        root = self.root.resolve()
        try:
            candidate.relative_to(root)
        except ValueError as exc:
            raise ValueError("ReportEngine only writes inside the DevPilot project root.") from exc
        return candidate


def build_report_id(command: str, *, subject: str | Path | None = None) -> str:
    """Build a stable report id from command and optional subject."""

    pieces = [command.replace(" ", "-")]
    if subject is not None:
        pieces.append(str(subject).replace("\\", "/"))
    return sanitize_report_id("-".join(pieces))


def sanitize_report_id(value: str) -> str:
    """Normalize a report id into a filesystem-safe basename."""

    value = value.strip().lower().replace("/", "-").replace("\\", "-")
    value = _SAFE_FILENAME_PATTERN.sub("-", value)
    value = re.sub(r"-+", "-", value).strip("-._")
    return value or "devpilot-report"


def render_markdown_report(report: EvidenceReport, *, output_paths: dict[str, str] | None = None) -> str:
    """Render a deterministic human-readable Markdown evidence report."""

    lines = [
        f"# DevPilot Evidence Report — {report.report_id}",
        "",
        "## Metadata",
        "",
        f"- Report ID: `{report.report_id}`",
        f"- Command: `{report.command}`",
        f"- Status: `{report.status.value}`",
        f"- OK: `{str(report.ok).lower()}`",
        f"- Exit code: `{report.exit_code}`",
        f"- Generated at: `{report.generated_at}`",
    ]
    if report.subject is not None:
        lines.append(f"- Subject: `{report.subject}`")
    if report.project_root is not None:
        lines.append(f"- Project root: `{report.project_root}`")
    if output_paths:
        lines.append(f"- JSON path: `{output_paths.get('json')}`")
        lines.append(f"- Markdown path: `{output_paths.get('markdown')}`")

    lines.extend(["", "## Message", "", report.message, "", "## Summary", ""])
    if report.summary:
        for key in sorted(report.summary):
            lines.append(f"- `{key}`: {report.summary[key]}")
    else:
        lines.append("No summary available.")

    lines.extend(["", "## Findings", ""])
    if report.findings:
        for finding in report.findings:
            severity = str(finding.get("severity", "info")).upper()
            finding_id = finding.get("id", "UNKNOWN")
            path = f" — `{finding['path']}`" if finding.get("path") else ""
            lines.append(f"- **{severity}** `{finding_id}`{path}: {finding.get('message', '')}")
    else:
        lines.append("No findings.")

    if report.metadata:
        lines.extend(["", "## Report Metadata", ""])
        for key in sorted(report.metadata):
            lines.append(f"- `{key}`: {report.metadata[key]}")

    lines.append("")
    return "\n".join(lines)


def _display_subject(subject: str | Path | None, root: Path) -> str | None:
    if subject is None:
        return None
    candidate = Path(subject)
    if candidate.is_absolute():
        return _relative(candidate, root)
    return str(candidate).replace("\\", "/")


def _relative(path: Path, root: Path) -> str:
    try:
        return str(path.resolve().relative_to(root.resolve())).replace("\\", "/")
    except ValueError:
        return str(path).replace("\\", "/")
