import { DevPilotApiClient, DevPilotApiError } from '../api/client';
import type { AiOperationItem, DevPilotApplicationResponse, GovernedJobSnapshot } from '../api/types';
import { renderContractBadges, renderUiStateNotice } from '../components/ContractBadges';

const OP_KEY='devpilot.uoc010.operation';
const APPROVAL_KEY='devpilot.uoc010.approval';

interface State {
  loading:boolean; catalog?:DevPilotApplicationResponse; status?:DevPilotApplicationResponse; plan?:DevPilotApplicationResponse; job?:DevPilotApplicationResponse; result?:DevPilotApplicationResponse; evidence?:DevPilotApplicationResponse;
  operationId:string; workspaceId:string; ragTarget:string; query:string; topK:number; indexSource:string; agentId:string; taskId:string; agentTarget:string; providerId:string; memoryOptIn:boolean; workflowId:string; handoffTarget:string; maxSteps:number; approvalId:string; errors:Record<string,string>;
}

export function renderAiOperationsView(tokenProvider:()=>string):HTMLElement {
  const section=document.createElement('section'); section.className='panel ai-console';
  const state:State={loading:false,operationId:sessionStorage.getItem(OP_KEY)||'rag-query',workspaceId:'devpilot-local',ragTarget:'docs',query:'¿Qué objetivo tiene DevPilot Local?',topK:5,indexSource:'canonical',agentId:'requirements.agent',taskId:'summarize-gaps',agentTarget:'requirements',providerId:'mock',memoryOptIn:false,workflowId:'repo-review',handoffTarget:'src',maxSteps:2,approvalId:sessionStorage.getItem(APPROVAL_KEY)||'',errors:{}};
  const client=()=>new DevPilotApiClient({token:tokenProvider()});

  async function bootstrap():Promise<void>{state.loading=true;draw();try{[state.catalog,state.status]=await Promise.all([client().aiOperations(),client().aiStatus()]);delete state.errors.bootstrap;const ops=operations();if(ops.length&&!ops.some(x=>x.operation_id===state.operationId))state.operationId=ops[0].operation_id;}catch(e){state.errors.bootstrap=msg(e);}state.loading=false;draw();}
  async function requestApproval():Promise<void>{const op=selected();if(!op)return;state.loading=true;draw();try{const r=await client().requestApproval({tool_id:op.capability_id.replace(/^cli\./,''),action:'execute',subject:op.operation_id,actor:'local-owner',reason:`UOC-010 ${op.operation_id} execution review`,scope:JSON.stringify({operation_id:op.operation_id,workspace_id:state.workspaceId,source:'ui.ai'}),ttl_minutes:60});const a=(r.data as {approval?:{approval_id?:string}}).approval;state.approvalId=a?.approval_id??'';sessionStorage.setItem(APPROVAL_KEY,state.approvalId);delete state.errors.approval;}catch(e){state.errors.approval=msg(e);}state.loading=false;draw();}
  async function planJob():Promise<void>{const op=selected();if(!op)return;state.loading=true;draw();try{state.plan=await client().aiPlanJob({operation_id:op.operation_id,workspace_id:state.workspaceId,parameters:parameters(),idempotency_key:`ui-ai-${op.operation_id}-${Date.now()}`,approval_id:state.approvalId||undefined});delete state.errors.plan;}catch(e){state.errors.plan=msg(e);}state.loading=false;draw();}
  async function executeJob():Promise<void>{const j=planned();if(!j)return;state.loading=true;draw();try{state.job=await client().aiExecuteJob(j.job_id);delete state.errors.execute;}catch(e){state.errors.execute=msg(e);}state.loading=false;draw();}
  async function refreshResult():Promise<void>{const j=planned();if(!j)return;state.loading=true;draw();try{state.result=await client().aiJobResult(j.job_id);state.job=await client().inspectJob(j.job_id);delete state.errors.result;}catch(e){state.errors.result=msg(e);}state.loading=false;draw();}
  async function packageEvidence():Promise<void>{state.loading=true;draw();try{state.evidence=await client().aiEvidencePackage(100);delete state.errors.evidence;}catch(e){state.errors.evidence=msg(e);}state.loading=false;draw();}

  function operations():AiOperationItem[]{return ((state.catalog?.data as {operations?:AiOperationItem[]}|undefined)?.operations??[])}
  function selected():AiOperationItem|undefined{return operations().find(x=>x.operation_id===state.operationId)}
  function selectors():Record<string,string[]>{return ((state.catalog?.data as {selectors?:Record<string,string[]>}|undefined)?.selectors??{})}
  function planned():GovernedJobSnapshot|undefined{return ((state.plan?.data as {job?:GovernedJobSnapshot}|undefined)?.job)??((state.job?.data as {job?:GovernedJobSnapshot}|undefined)?.job)}
  function parameters():Record<string,unknown>{if(state.operationId==='rag-index')return{target_id:state.ragTarget};if(state.operationId==='rag-query')return{query:state.query,top_k:state.topK,index_source:state.indexSource};if(state.operationId==='agent-run')return{agent_id:state.agentId,task_id:state.taskId,target_id:state.agentTarget,provider_id:state.providerId,memory_opt_in:state.memoryOptIn};return{workflow_id:state.workflowId,target_id:state.handoffTarget,max_steps:state.maxSteps};}

  function draw():void{
    section.replaceChildren();const head=document.createElement('div');head.className='viewer-panel__header';head.innerHTML='<div><h2>IA / RAG gobernados</h2><p>RAG local con citas, agentes mock/local opt-in, tools contract-only y handoffs supervisados.</p></div>';head.append(renderContractBadges('ui.ai',{warning:'Mock obligatorio · local opt-in · External API OFF · no remote/connector/plugin · memoria no es evidencia.'}));section.append(head);
    if(state.loading)section.append(renderUiStateNotice('loading','Procesando operación IA gobernada local.'));for(const [k,v] of Object.entries(state.errors))section.append(renderUiStateNotice('error',`${k}: ${v}`));if(!state.catalog){section.append(renderUiStateNotice('empty','Aplica el token local para cargar IA / RAG.'));return;}
    section.append(statusPanel());const grid=document.createElement('div');grid.className='ai-grid';grid.append(plannerPanel(),resultPanel());section.append(grid);const evidence=document.createElement('article');evidence.className='viewer-card';evidence.innerHTML='<h3>Evidencia local</h3><p>Empaqueta resultados UOC-010 bajo outputs; memoria opt-in se referencia pero nunca cuenta como evidencia formal.</p>';const eb=document.createElement('button');eb.textContent='Empaquetar evidencia';eb.addEventListener('click',()=>void packageEvidence());evidence.append(eb);if(state.evidence){const pre=document.createElement('pre');pre.className='viewer-pre';pre.textContent=JSON.stringify(state.evidence.data,null,2);evidence.append(pre);}section.append(evidence);
  }
  function statusPanel():HTMLElement{const a=document.createElement('article');a.className='viewer-card ai-status';a.innerHTML='<h3>Estado de proveedores y guardrails</h3>';const d=state.status?.data as any;const cards=document.createElement('div');cards.className='ai-status-grid';for(const item of [
    ['Modelo',`Mock: ${d?.summary?.mock_mandatory?'obligatorio':'?'}; local: opt-in; externa: ${d?.summary?.external_api_enabled?'ON':'OFF'}`],
    ['RAG',d?.rag?.canonical_index?.generated_at_utc?`Índice canónico: ${d.rag.canonical_index.generated_at_utc}`:'Índice canónico no disponible'],
    ['Tools',`Modo: ${d?.tool_contract?.execution_mode??'contract-only'} · genérico: NO`],
    ['Memoria',`Default: OFF · retención 14d · evidencia formal: NO`],
    ['Handoffs','Supervisor explícito · repo-review · máximo 3 pasos'],
  ]){const c=document.createElement('div');c.className='ai-status-card';c.innerHTML=`<strong>${item[0]}</strong><span>${item[1]}</span>`;cards.append(c);}a.append(cards);const providers=document.createElement('details');const s=document.createElement('summary');s.textContent='Ver proveedores registrados';providers.append(s);const pre=document.createElement('pre');pre.className='viewer-pre';pre.textContent=JSON.stringify(d?.providers??[],null,2);providers.append(pre);a.append(providers);return a;}
  function plannerPanel():HTMLElement{const p=document.createElement('article');p.className='viewer-card';p.innerHTML='<h3>Planificador IA gobernado</h3><p>Solo IDs registrados. No acepta comandos, plugins, conectores, endpoints remotos ni tools libres.</p>';const opSel=selectInput('Operación',state.operationId,operations().map(x=>x.operation_id),v=>{state.operationId=v;sessionStorage.setItem(OP_KEY,v);state.plan=undefined;state.job=undefined;state.result=undefined;draw();},v=>operations().find(x=>x.operation_id===v)?.label??v);p.append(opSel,textInput('Workspace ID',state.workspaceId,v=>state.workspaceId=v));const op=selected();if(op){const b=document.createElement('p');b.className='quality-budget';b.textContent=`Budget ${op.timeout_seconds}s · approval ${op.requires_approval?'sí':'no'} · cancel ${op.supports_cancel?'sí':'no'} · ${op.capability_id}`;p.append(b);}
    if(state.operationId==='rag-index')p.append(selectInput('Target RAG',state.ragTarget,selectors().rag_targets??['docs'],v=>state.ragTarget=v));
    if(state.operationId==='rag-query')p.append(textArea('Consulta',state.query,v=>state.query=v),numberInput('Top K',state.topK,1,10,v=>state.topK=v),selectInput('Fuente del índice',state.indexSource,selectors().rag_index_sources??['canonical'],v=>state.indexSource=v));
    if(state.operationId==='agent-run'){p.append(selectInput('Agente',state.agentId,selectors().agents??[],v=>state.agentId=v),selectInput('Tarea tipada',state.taskId,selectors().agent_tasks??[],v=>state.taskId=v),selectInput('Target',state.agentTarget,selectors().agent_targets??[],v=>state.agentTarget=v),selectInput('Proveedor',state.providerId,enabledProviders(),v=>state.providerId=v));const mem=document.createElement('label');mem.className='checkbox-line';const cb=document.createElement('input');cb.type='checkbox';cb.checked=state.memoryOptIn;cb.addEventListener('change',()=>state.memoryOptIn=cb.checked);mem.append(cb,document.createTextNode(' Memoria local opt-in (redactada, 14 días, no evidencia formal)'));p.append(mem);}
    if(state.operationId==='handoff-run')p.append(selectInput('Workflow',state.workflowId,selectors().workflows??['repo-review'],v=>state.workflowId=v),selectInput('Target',state.handoffTarget,selectors().handoff_targets??['src'],v=>state.handoffTarget=v),numberInput('Máximo de pasos',state.maxSteps,1,3,v=>state.maxSteps=v));
    if(op?.requires_approval){const box=document.createElement('div');box.className='quality-approval';box.innerHTML=`<strong>Approval requerido</strong><p>${state.approvalId?`Approval conservado: ${state.approvalId}`:'Solicita approval y aprueba exactamente el mismo ID en Approval Center.'}</p>`;const rb=document.createElement('button');rb.className='button-secondary';rb.textContent='Crear solicitud de approval';rb.addEventListener('click',()=>void requestApproval());const l=document.createElement('a');l.href='/approvals';l.textContent='Abrir Approval Center';box.append(rb,l,textInput('Approval ID aprobado',state.approvalId,v=>{state.approvalId=v;sessionStorage.setItem(APPROVAL_KEY,v);}));p.append(box);}
    const plan=document.createElement('button');plan.textContent='Crear plan inmutable';plan.addEventListener('click',()=>void planJob());p.append(plan);const j=planned();if(j){const exec=document.createElement('button');exec.textContent='Ejecutar job tipado';exec.addEventListener('click',()=>void executeJob());const refresh=document.createElement('button');refresh.className='button-secondary';refresh.textContent='Actualizar resultado';refresh.addEventListener('click',()=>void refreshResult());const link=document.createElement('a');link.href=`/jobs/${j.job_id}`;link.textContent=`Abrir Job Console · ${j.job_id}`;p.append(exec,refresh,link);}return p;}
  function resultPanel():HTMLElement{const r=document.createElement('article');r.className='viewer-card';r.innerHTML='<h3>Resultado, trazas y grounding</h3><p>Los resultados muestran proveedor/costo, citas/freshness, insufficient-evidence, memory receipt o handoff trace según corresponda.</p>';const data=(state.result?.data as any)?.result??state.plan?.data??{};const pre=document.createElement('pre');pre.className='viewer-pre';pre.textContent=JSON.stringify(data,null,2);r.append(pre);return r;}
  function enabledProviders():string[]{const providers=((state.status?.data as any)?.providers??[]) as any[];const values=providers.filter(x=>x.enabled&&!x.external_api&&(x.kind==='mock'||x.kind==='local')).map(x=>String(x.provider_id));return values.length?values:['mock'];}
  function msg(e:unknown):string{if(e instanceof DevPilotApiError)return e.message;return e instanceof Error?e.message:String(e);}
  function textInput(label:string,value:string,set:(v:string)=>void):HTMLElement{const l=document.createElement('label');l.textContent=label;const i=document.createElement('input');i.value=value;i.addEventListener('input',()=>set(i.value));l.append(i);return l;}
  function textArea(label:string,value:string,set:(v:string)=>void):HTMLElement{const l=document.createElement('label');l.textContent=label;const i=document.createElement('textarea');i.rows=4;i.value=value;i.addEventListener('input',()=>set(i.value));l.append(i);return l;}
  function numberInput(label:string,value:number,min:number,max:number,set:(v:number)=>void):HTMLElement{const l=document.createElement('label');l.textContent=label;const i=document.createElement('input');i.type='number';i.min=String(min);i.max=String(max);i.value=String(value);i.addEventListener('input',()=>set(Number(i.value)));l.append(i);return l;}
  function selectInput(label:string,value:string,values:string[],set:(v:string)=>void,format:(v:string)=>string=(v)=>v):HTMLElement{const l=document.createElement('label');l.textContent=label;const s=document.createElement('select');for(const v of values){const o=document.createElement('option');o.value=v;o.textContent=format(v);o.selected=v===value;s.append(o);}s.addEventListener('change',()=>set(s.value));l.append(s);return l;}
  void bootstrap();return section;
}
