import { DevPilotApiClient } from '../api/client';

type EntryMode='CREATE_NEW'|'OPEN_EXISTING'|'IMPORT_GIT';

export function renderProjectEntryDryRunView(): HTMLElement {
  const root=document.createElement('section'); root.className='project-entry-workbench'; root.dataset.gsdlc03c='dry-run-workbench';
  const intro=document.createElement('div'); intro.className='project-entry-hero';
  const eyebrow=document.createElement('p'); eyebrow.className='project-entry-eyebrow'; eyebrow.textContent='GSDLC-03-C · planning only';
  const h=document.createElement('h2'); h.textContent='Revisar Create / Open / Import antes de ejecutar';
  const p=document.createElement('p'); p.textContent='Genera un dry-run verificable con plan hash, preimage hash, efectos declarados y preview de aprobación. Esta vista no crea archivos, no clona repositorios y no instala dependencias.';
  intro.append(eyebrow,h,p);
  const form=document.createElement('form'); form.className='project-entry-form'; form.noValidate=true;
  const mode=selectField('Modo de entrada','entry-mode',[['CREATE_NEW','Crear nuevo'],['OPEN_EXISTING','Abrir existente'],['IMPORT_GIT','Importar Git']]);
  const projectId=inputField('Project ID','project-id','gsdlc03c-demo'); const projectName=inputField('Nombre','project-name','GSDLC 03-C demo'); const target=inputField('Ruta destino / workspace *','target-root','');
  const sourceKind=selectField('Tipo de origen Git','git-source-kind',[['local-path','Repositorio local'],['remote-url','URL remota · plan-only']]);
  const source=inputField('Ruta / URL de origen Git','git-source-location','');
  const grid=document.createElement('div'); grid.className='project-entry-form-grid'; grid.append(mode.wrapper,projectId.wrapper,projectName.wrapper,target.wrapper,sourceKind.wrapper,source.wrapper);
  const hint=document.createElement('p'); hint.className='project-entry-hint'; hint.textContent='IMPORT_GIT usa el origen Git. Para CREATE_NEW y OPEN_EXISTING el origen se ignora. Remote Git nunca contacta la red en 03-C.';
  const buttons=document.createElement('div'); buttons.className='project-entry-actions';
  const dry=document.createElement('button'); dry.type='submit'; dry.textContent='Generar dry-run';
  const revalidate=document.createElement('button'); revalidate.type='button'; revalidate.textContent='Revalidar preimage'; revalidate.disabled=true;
  buttons.append(dry,revalidate); form.append(grid,hint,buttons);
  const status=document.createElement('div'); status.className='project-entry-status'; status.setAttribute('role','status'); status.setAttribute('aria-live','polite');
  const result=document.createElement('div'); result.className='project-entry-result'; result.dataset.state='empty';
  let lastIntake:Record<string,unknown>|null=null, lastPlan='', lastPreimage='';
  const client=new DevPilotApiClient();
  const sync=()=>{const isImport=mode.select.value==='IMPORT_GIT'; sourceKind.select.disabled=!isImport; source.input.disabled=!isImport;}; mode.select.addEventListener('change',sync); sync();
  form.addEventListener('submit',async(ev)=>{ev.preventDefault(); const projectIdValue=projectId.input.value.trim(); const projectNameValue=projectName.input.value.trim(); const targetValue=target.input.value.trim(); const sourceValue=source.input.value.trim(); if(!projectIdValue){status.textContent='BLOCK: Project ID es obligatorio.'; result.replaceChildren(); result.dataset.state='error'; projectId.input.focus(); return;} if(!projectNameValue){status.textContent='BLOCK: Nombre es obligatorio.'; result.replaceChildren(); result.dataset.state='error'; projectName.input.focus(); return;} if(!targetValue){status.textContent='BLOCK: la Ruta destino / workspace es obligatoria y debe permanecer dentro de una raíz de workspace autorizada.'; result.replaceChildren(); result.dataset.state='error'; target.input.focus(); return;} if(mode.select.value==='IMPORT_GIT'&&!sourceValue){status.textContent='BLOCK: IMPORT_GIT requiere una Ruta / URL de origen Git.'; result.replaceChildren(); result.dataset.state='error'; source.input.focus(); return;} status.textContent='Generando dry-run read-only…'; result.replaceChildren(); result.dataset.state='loading'; dry.disabled=true; revalidate.disabled=true; try {
    const intake=buildIntake(mode.select.value as EntryMode,projectIdValue,projectNameValue,targetValue,sourceKind.select.value,sourceValue); lastIntake=intake;
    const response=await client.projectEntryDryRun({intake}); const data=response.data as Record<string,unknown>; const preview=(data.dry_run??{}) as Record<string,unknown>; lastPlan=String(preview.plan_hash??''); lastPreimage=String(preview.preimage_hash??'');
    renderPreview(result,preview,(data.bootstrap_plan??{}) as Record<string,unknown>); result.dataset.state='ready'; status.textContent='PASS: dry-run generado sin writes ni network.'; revalidate.disabled=!(lastPlan&&lastPreimage);
  } catch(error){result.dataset.state='error'; status.textContent=`BLOCK: ${error instanceof Error?error.message:'No fue posible generar el dry-run.'}`;} finally {dry.disabled=false;}});
  revalidate.addEventListener('click',async()=>{if(!lastIntake||!lastPlan||!lastPreimage)return; status.textContent='Revalidando preimage…'; revalidate.disabled=true; try{const response=await client.projectEntryRevalidate({intake:lastIntake,expected_plan_hash:lastPlan,expected_preimage_hash:lastPreimage}); const ok=response.ok===true; status.textContent=ok?'PASS: plan y preimage permanecen inmutables.':'BLOCK: el preimage cambió; genera un nuevo dry-run.';}catch(error){status.textContent=`BLOCK: ${error instanceof Error?error.message:'Revalidación falló.'}`;}finally{revalidate.disabled=false;}});
  const noExecute=document.createElement('div'); noExecute.className='project-entry-no-execute'; noExecute.textContent='Ejecución deshabilitada en GSDLC-03-C. El paso execute/rollback pertenece a GSDLC-03-D.';
  root.append(intro,form,status,noExecute,result); return root;
}

function buildIntake(mode:EntryMode,id:string,name:string,target:string,sourceKind:string,source:string):Record<string,unknown>{const intake:Record<string,unknown>={schema_id:'SCHEMA-DEVPL-GSDLC-03-A-PROJECT-INTAKE-V1',schema_version:'1.0',project_id:id.trim(),project_name:name.trim(),project_type:'agent-assisted-sdlc',entry_mode:mode,target_root:target.trim(),stack:{frontend:'react-typescript',backend:'fastapi-python',database:'sqlite'},standards:['MIPSoftware','MIASI'],provider:{mode:'none',provider_id:null},restrictions:{arbitrary_shell_allowed:false,silent_network_allowed:false,remote_git_execute_allowed:false}}; if(mode==='IMPORT_GIT')intake.git_source={kind:sourceKind,location:source.trim()}; return intake;}
function inputField(label:string,id:string,value:string){const wrapper=document.createElement('label');wrapper.className='project-entry-field';wrapper.htmlFor=id;const span=document.createElement('span');span.textContent=label;const input=document.createElement('input');input.id=id;input.value=value;input.autocomplete='off';input.required=true;wrapper.append(span,input);return{wrapper,input};}
function selectField(label:string,id:string,items:[string,string][]){const wrapper=document.createElement('label');wrapper.className='project-entry-field';wrapper.htmlFor=id;const span=document.createElement('span');span.textContent=label;const select=document.createElement('select');select.id=id;for(const[v,t]of items){const o=document.createElement('option');o.value=v;o.textContent=t;select.append(o);}wrapper.append(span,select);return{wrapper,select};}
function renderPreview(target:HTMLElement,dry:Record<string,unknown>,plan:Record<string,unknown>){const review=(dry.review??{}) as Record<string,unknown>;const approval=(dry.approval_preview??{}) as Record<string,unknown>;const safety=(dry.safety??{}) as Record<string,unknown>;const top=document.createElement('div');top.className='project-entry-summary-grid'; for(const[label,value]of [['Modo',review.entry_mode],['Plan hash',dry.plan_hash],['Preimage hash',dry.preimage_hash],['Writes ejecutados',safety.writes_performed],['Network usada',safety.network_used],['Approval solicitado',safety.approval_requested]]){const c=document.createElement('div');c.className='project-entry-summary-card';const k=document.createElement('span');k.textContent=String(label);const v=document.createElement('strong');v.textContent=String(value??'—');c.append(k,v);top.append(c);} const details=document.createElement('div');details.className='project-entry-review-grid';details.append(jsonCard('Preview de aprobación',approval),jsonCard('Efectos declarados',{directories:plan.directories,files:plan.files,git_operations:plan.git_operations,venv:plan.venv,dependency_jobs:plan.dependency_jobs,workspace_registration:plan.workspace_registration,network:plan.network}),jsonCard('Preimage',dry.preimage)); target.append(top,details);}
function jsonCard(title:string,payload:unknown){const card=document.createElement('article');card.className='project-entry-review-card';const h=document.createElement('h3');h.textContent=title;const pre=document.createElement('pre');pre.textContent=JSON.stringify(payload,null,2);card.append(h,pre);return card;}
