import { DevPilotApiClient, DevPilotApiError } from '../api/client';
import type { DevPilotApplicationResponse, GovernedJobSnapshot, QualityOperationItem } from '../api/types';
import { renderContractBadges } from '../components/ContractBadges';
import { renderUiStateNotice } from '../components/ContractBadges';

const FULL_CONFIRMATION = 'RUN FULL REGRESSION';

interface State {
  loading: boolean; catalog?: DevPilotApplicationResponse; baseline?: DevPilotApplicationResponse; impact?: DevPilotApplicationResponse; plan?: DevPilotApplicationResponse; job?: DevPilotApplicationResponse; evidence?: DevPilotApplicationResponse;
  operationId: string; workspaceId: string; qualityProfile: string; tcrProfile: string; changedPaths: string; approvalId: string; fullConfirmation: string; errors: Record<string,string>;
}

export function renderQualityOperationsView(tokenProvider: () => string): HTMLElement {
  const section=document.createElement('section'); section.className='panel quality-console';
  const state: State={loading:false,operationId:'test-impact',workspaceId:'devpilot-local',qualityProfile:'fast',tcrProfile:'p0-critical',changedPaths:'README.md',approvalId:'',fullConfirmation:'',errors:{}};

  const client=()=>new DevPilotApiClient({token:tokenProvider()});
  async function bootstrap(): Promise<void> { state.loading=true; draw(); try { [state.catalog,state.baseline]=await Promise.all([client().qualityOperations(),client().qualityBaseline()]); delete state.errors.bootstrap; const ops=operations(); if (ops.length && !ops.some(x=>x.operation_id===state.operationId)) state.operationId=ops[0].operation_id; } catch(e){state.errors.bootstrap=message(e);} state.loading=false; draw(); }
  async function planImpact(): Promise<void> { state.loading=true; draw(); try { const paths=state.changedPaths.split(/\r?\n/).map(x=>x.trim()).filter(Boolean); state.impact=await client().qualityTestImpact(paths); delete state.errors.impact; } catch(e){state.errors.impact=message(e);} state.loading=false; draw(); }
  async function requestApproval(): Promise<void> { const op=selectedOperation(); if(!op) return; state.loading=true; draw(); try { const response=await client().requestApproval({tool_id:op.capability_id.replace(/^cli\./,''),action:'execute',subject:op.operation_id,actor:'local-owner',reason:`UOC-009 ${op.operation_id} execution review`,scope:JSON.stringify({operation_id:op.operation_id,workspace_id:state.workspaceId,source:'ui.quality'}),ttl_minutes:60}); const approval=(response.data as {approval?:{approval_id?:string}}).approval; state.approvalId=approval?.approval_id ?? ''; delete state.errors.approval; } catch(e){state.errors.approval=approvalErrorMessage(e);} state.loading=false; draw(); }
  async function planJob(): Promise<void> { const op=selectedOperation(); if(!op) return; state.loading=true; draw(); const parameters:Record<string,unknown>={}; if(op.operation_id==='quality-gate') parameters.profile=state.qualityProfile; if(op.operation_id==='focused-tests') parameters.tcr_profile=state.tcrProfile; if(op.operation_id==='full-regression') parameters.confirmation=state.fullConfirmation; if(op.operation_id==='test-impact') parameters.changed_paths=state.changedPaths.split(/\r?\n/).map(x=>x.trim()).filter(Boolean); if(op.operation_id==='evidence-package') parameters.limit=100; try { state.plan=await client().qualityPlanJob({operation_id:op.operation_id,workspace_id:state.workspaceId,parameters,idempotency_key:`ui-${op.operation_id}-${Date.now()}`,approval_id:state.approvalId || undefined,full_regression_confirmation:op.operation_id==='full-regression'?state.fullConfirmation:undefined}); delete state.errors.plan; } catch(e){state.errors.plan=message(e);} state.loading=false; draw(); }
  async function executeJob(): Promise<void> { const job=plannedJob(); if(!job) return; state.loading=true; draw(); try { state.job=await client().qualityExecuteJob(job.job_id); delete state.errors.execute; } catch(e){state.errors.execute=message(e);} state.loading=false; draw(); }
  async function refreshJob(): Promise<void> { const job=plannedJob(); if(!job) return; state.loading=true; draw(); try { state.job=await client().inspectJob(job.job_id); delete state.errors.job; } catch(e){state.errors.job=message(e);} state.loading=false; draw(); }
  async function packageEvidence(): Promise<void> { state.loading=true; draw(); try { state.evidence=await client().qualityEvidencePackage(100); delete state.errors.evidence; } catch(e){state.errors.evidence=message(e);} state.loading=false; draw(); }

  function operations(): QualityOperationItem[] { return ((state.catalog?.data as {operations?:QualityOperationItem[]} | undefined)?.operations ?? []); }
  function selectedOperation(): QualityOperationItem | undefined { return operations().find(x=>x.operation_id===state.operationId); }
  function selectors(): {tcr_profiles?:string[];quality_gate_profiles?:string[]} { return ((state.baseline?.data as {selectors?:{tcr_profiles?:string[];quality_gate_profiles?:string[]}}|undefined)?.selectors ?? {}); }
  function tcrProfiles(): string[] { const values=selectors().tcr_profiles ?? []; return values.length?values:['p0-critical']; }
  function qualityProfiles(): string[] { const values=selectors().quality_gate_profiles ?? []; return values.length?values:['fast']; }
  function plannedJob(): GovernedJobSnapshot | undefined { return ((state.plan?.data as {job?:GovernedJobSnapshot}|undefined)?.job) ?? ((state.job?.data as {job?:GovernedJobSnapshot}|undefined)?.job); }

  function draw(): void {
    section.replaceChildren(); const header=document.createElement('div'); header.className='viewer-panel__header'; const intro=document.createElement('div'); intro.innerHTML='<h2>Quality, tests y release</h2><p>Operaciones determinísticas con Test Impact, budgets, approvals, heartbeat y evidencia reproducible.</p>'; intro.append(renderContractBadges('ui.quality',{warning:'Local-first · selección por registry ID · no shell · full regression nunca automática.'})); header.append(intro); section.append(header);
    if(state.loading) section.append(renderUiStateNotice('loading','Procesando operación gobernada local.')); for(const [k,v] of Object.entries(state.errors)) section.append(renderUiStateNotice('error',`${k}: ${v}`));
    if(!state.catalog){ section.append(renderUiStateNotice('empty','Aplica el token local para cargar el catálogo de Quality/Tests/Release.')); return; }
    const base=document.createElement('article'); base.className='viewer-card quality-baseline'; base.innerHTML='<h3>Baseline y contrato</h3>'; const bp=document.createElement('pre'); bp.className='viewer-pre'; bp.textContent=JSON.stringify(state.baseline?.data ?? {},null,2); base.append(bp); section.append(base);
    const grid=document.createElement('div'); grid.className='quality-grid';
    const planner=document.createElement('article'); planner.className='viewer-card'; planner.innerHTML='<h3>Planificador gobernado</h3><p>Selecciona una capacidad registrada; no se aceptan comandos, rutas de ejecutables ni argumentos pytest libres.</p>';
    const opLabel=document.createElement('label'); opLabel.textContent='Operación'; const select=document.createElement('select'); for(const op of operations()){const o=document.createElement('option');o.value=op.operation_id;o.textContent=`${op.label} · ${op.risk_class}`;o.selected=op.operation_id===state.operationId;select.append(o);} select.addEventListener('change',()=>{state.operationId=select.value;state.plan=undefined;draw();}); opLabel.append(select); planner.append(opLabel);
    const op=selectedOperation(); if(op){ const budget=document.createElement('p'); budget.className='quality-budget'; budget.textContent=`Budget: ${op.timeout_seconds}s · approval: ${op.requires_approval?'sí':'no'} · cancel: ${op.supports_cancel?'sí':'no'} · ${op.capability_id}`; planner.append(budget); }
    planner.append(textInput('Workspace ID',state.workspaceId,v=>state.workspaceId=v));
    if(state.operationId==='quality-gate') planner.append(selectInput('Quality profile',state.qualityProfile,qualityProfiles(),v=>state.qualityProfile=v));
    if(state.operationId==='focused-tests') planner.append(selectInput('TCR profile',state.tcrProfile,tcrProfiles(),v=>state.tcrProfile=v));
    if(state.operationId==='full-regression'){ const warning=document.createElement('div');warning.className='ui-state ui-state--block';warning.textContent='Full regression: requiere approval, presupuesto explícito y confirmación exacta. No se ejecuta después de focused tests.';planner.append(warning,textInput(`Escriba exactamente: ${FULL_CONFIRMATION}`,state.fullConfirmation,v=>state.fullConfirmation=v)); }
    if(state.operationId==='test-impact'){ const lab=document.createElement('label');lab.textContent='Changed paths — uno por línea, relativos al repo';const ta=document.createElement('textarea');ta.value=state.changedPaths;ta.rows=5;ta.addEventListener('input',()=>state.changedPaths=ta.value);lab.append(ta);planner.append(lab); const b=document.createElement('button');b.textContent='Planificar Test Impact';b.addEventListener('click',()=>void planImpact());planner.append(b); }
    if(op?.requires_approval){ const a=document.createElement('div');a.className='quality-approval';a.innerHTML=`<strong>Approval requerido</strong><p>${state.approvalId?`Solicitud: ${state.approvalId}`:'Crea la solicitud, apruébala manualmente en Approval Center y conserva el Approval ID.'}</p>`;const req=document.createElement('button');req.className='button-secondary';req.textContent='Crear solicitud de approval';req.addEventListener('click',()=>void requestApproval());const link=document.createElement('a');link.href='/approvals';link.textContent='Abrir Approval Center';a.append(req,link,textInput('Approval ID aprobado',state.approvalId,v=>state.approvalId=v)); planner.append(a); }
    const plan=document.createElement('button');plan.textContent='Crear plan inmutable';plan.disabled=state.loading;plan.addEventListener('click',()=>void planJob());planner.append(plan);
    grid.append(planner);
    const obs=document.createElement('article');obs.className='viewer-card';obs.innerHTML='<h3>Resultado y observabilidad</h3><p>Los jobs largos se observan en Job Console con heartbeat, timeout, cancelación y failure replay.</p>'; const job=plannedJob(); if(job){ const p=document.createElement('p');p.innerHTML=`<strong>${job.status.toUpperCase()}</strong> · ${job.job_id}`;obs.append(p); const counts=((state.job?.data as {job?:{result_summary?:{counts?:Record<string,unknown>}}}|undefined)?.job?.result_summary?.counts); if(counts && ['passed','failed','errors','skipped'].some(k=>k in counts)){const c=document.createElement('div');c.className='quality-test-counts';for(const k of ['passed','failed','errors','skipped']){const span=document.createElement('span');span.textContent=`${k}: ${String(counts[k] ?? 0)}`;c.append(span);}obs.append(c);} const link=document.createElement('a');link.href=`/jobs/${encodeURIComponent(job.job_id)}`;link.textContent='Abrir en Job Console';obs.append(link); const controls=document.createElement('div');controls.className='viewer-controls';const ex=document.createElement('button');ex.textContent='Ejecutar job tipado';ex.disabled=state.loading||!['planned','approved','queued'].includes(job.status);ex.addEventListener('click',()=>void executeJob());const rf=document.createElement('button');rf.className='button-secondary';rf.textContent='Actualizar resultado';rf.addEventListener('click',()=>void refreshJob());controls.append(ex,rf);obs.append(controls); } else obs.append(renderUiStateNotice('empty','Todavía no existe un job planificado.')); const pre=document.createElement('pre');pre.className='viewer-pre quality-result';pre.textContent=JSON.stringify(state.job?.data ?? state.plan?.data ?? state.impact?.data ?? {},null,2);obs.append(pre); grid.append(obs); section.append(grid);
    const evidence=document.createElement('article');evidence.className='viewer-card';evidence.innerHTML='<h3>Evidencia local</h3><p>Empaqueta resultados UOC-009 bajo outputs; no incluye secretos ni modifica source.</p>';const eb=document.createElement('button');eb.textContent='Empaquetar evidencia';eb.addEventListener('click',()=>void packageEvidence());evidence.append(eb);if(state.evidence){const ep=document.createElement('pre');ep.className='viewer-pre';ep.textContent=JSON.stringify(state.evidence.data,null,2);evidence.append(ep);} section.append(evidence);
  }
  function textInput(labelText:string,value:string,setter:(v:string)=>void):HTMLElement{const l=document.createElement('label');l.textContent=labelText;const i=document.createElement('input');i.value=value;i.addEventListener('input',()=>setter(i.value));l.append(i);return l;}
  function selectInput(labelText:string,value:string,values:string[],setter:(v:string)=>void):HTMLElement{const l=document.createElement('label');l.textContent=labelText;const s=document.createElement('select');for(const v of values){const o=document.createElement('option');o.value=v;o.textContent=v;o.selected=v===value;s.append(o);}s.addEventListener('change',()=>setter(s.value));l.append(s);return l;}
  function approvalErrorMessage(error:unknown):string {
    if (error instanceof DevPilotApiError && error.status === 403) {
      const payload=error.payload as Partial<DevPilotApplicationResponse>;
      const findings=Array.isArray(payload.findings)?payload.findings:[];
      const finding=findings.find(item=>typeof item?.message==='string');
      const detail=payload.message ?? finding?.message ?? 'solicitud bloqueada por policy o contrato después de autenticar el token local.';
      return `Approval BLOCK 403: ${detail}`;
    }
    return message(error);
  }
  function message(error:unknown):string{return error instanceof Error?error.message:String(error);}
  draw(); if(tokenProvider()) void bootstrap(); return section;
}
