import { DevPilotApiClient, DevPilotApiError } from '../api/client';
import type { ReleaseLifecyclePlan } from '../api/types';

function fact(label:string,value:unknown):HTMLElement{const r=document.createElement('div');r.className='release-lifecycle-fact';const k=document.createElement('strong');k.textContent=label;const v=document.createElement('span');v.textContent=String(value??'—');r.append(k,v);return r;}
function card(title:string,body:string):HTMLElement{const a=document.createElement('article');a.className='panel';const h=document.createElement('h3');h.textContent=title;const p=document.createElement('p');p.textContent=body;a.append(h,p);return a;}
function renderPlan(plan:ReleaseLifecyclePlan):HTMLElement{const a=card('Plan dry-run listo',`Operación: ${plan.operation}. Revise autoridad y target antes de ejecutar.`);const f=document.createElement('div');f.className='release-lifecycle-facts';f.append(fact('Commit',plan.source_authority.commit),fact('Tree',plan.source_authority.tree),fact('Target',plan.target),fact('Plan hash',plan.plan_hash));a.append(f);return a;}
function renderState(payload:any):HTMLElement{const w=document.createElement('div');w.className='release-lifecycle-result';const hero=card('Install, upgrade and rollback',`Estado actual: ${payload?.state??'NOT_STARTED'}. El flujo opera solo sobre un sandbox local controlado.`);const lc=payload?.lifecycle??{};const f=document.createElement('div');f.className='release-lifecycle-facts';const install=lc.install_result??{};const upgrade=lc.upgrade_result??{};const rollback=lc.rollback_result??{};f.append(fact('Install',install.status??'PENDING'),fact('Install tree SHA-256',install.installed_tree_sha256??'—'),fact('Upgrade',upgrade.status??'PENDING'),fact('Backup SHA-256',upgrade.backup?.zip_sha256??'—'),fact('Rollback',rollback.status??'PENDING'),fact('Restore hash parity',rollback.hash_parity===true?'PASS':rollback.hash_parity===false?'BLOCK':'—'),fact('Fault marker absent',rollback.fault_marker_absent===true?'PASS':rollback.fault_marker_absent===false?'BLOCK':'—'));hero.append(f);const boundary=card('Límites de autoridad','Local-only y sandbox-only. No producción, publish, deploy, tag, package-manager ni red. La aprobación separada para targets no-sandbox queda fuera de esta primera versión.');w.append(hero,boundary);return w;}

export function renderReleaseLifecycleView(tokenProvider:()=>string|null):HTMLElement{
  const section=document.createElement('section');section.className='release-lifecycle-view';section.dataset.uiRouteId='ui.release-lifecycle';
  const intro=document.createElement('div');const h=document.createElement('h2');h.textContent='Install, upgrade and rollback workflows';const p=document.createElement('p');p.textContent='Secuencia gobernada: package prerequisite → clean install → backup-before-upgrade → fault injection controlada → rollback verificado por hash/capability.';intro.append(h,p);
  const actions=document.createElement('div');actions.className='release-lifecycle-actions';
  const refresh=document.createElement('button');refresh.textContent='Actualizar estado';
  const installPlan=document.createElement('button');installPlan.textContent='1. Plan clean install';
  const installExec=document.createElement('button');installExec.textContent='2. Ejecutar install smoke';installExec.disabled=true;
  const upgradePlan=document.createElement('button');upgradePlan.textContent='3. Plan upgrade + backup';upgradePlan.disabled=true;
  const upgradeExec=document.createElement('button');upgradeExec.textContent='4. Ejecutar upgrade controlado';upgradeExec.disabled=true;
  const rollbackPlan=document.createElement('button');rollbackPlan.textContent='5. Plan rollback';rollbackPlan.disabled=true;
  const rollbackExec=document.createElement('button');rollbackExec.textContent='6. Ejecutar rollback';rollbackExec.disabled=true;
  actions.append(refresh,installPlan,installExec,upgradePlan,upgradeExec,rollbackPlan,rollbackExec);section.append(intro,actions);
  const content=document.createElement('div');content.className='release-lifecycle-content';section.append(content);
  const api=()=>new DevPilotApiClient({token:tokenProvider()});let pInstall:ReleaseLifecyclePlan|null=null,pUpgrade:ReleaseLifecyclePlan|null=null,pRollback:ReleaseLifecyclePlan|null=null;
  const err=(e:unknown)=>{const a=card('Operación bloqueada',e instanceof DevPilotApiError?e.message:e instanceof Error?e.message:String(e));a.append(card('Siguiente acción','No fuerce el estado. Corrija la precondición indicada y vuelva a ejecutar solo la fase pendiente.'));content.replaceChildren(a);};
  const load=async()=>{try{const r=await api().releaseLifecycleStatus();content.replaceChildren(renderState(r.data));const st=(r.data as any)?.state;upgradePlan.disabled=!(st==='INSTALLED'||st==='ROLLBACK_VERIFIED');rollbackPlan.disabled=st!=='ROLLBACK_REQUIRED';}catch(e){err(e);}};
  installPlan.onclick=()=>void(async()=>{try{const r=await api().releaseLifecycleInstallPlan();pInstall=r.data?.plan??null;if(!pInstall)throw new Error('InstallPlan ausente.');content.replaceChildren(renderPlan(pInstall));installExec.disabled=false;}catch(e){err(e);}})();
  installExec.onclick=()=>void(async()=>{if(!pInstall)return;installExec.disabled=true;try{await api().releaseLifecycleInstallExecute(pInstall.plan_id,pInstall.plan_hash);upgradePlan.disabled=false;await load();}catch(e){err(e);installExec.disabled=false;}})();
  upgradePlan.onclick=()=>void(async()=>{try{const r=await api().releaseLifecycleUpgradePlan();pUpgrade=r.data?.plan??null;if(!pUpgrade)throw new Error('UpgradePlan ausente.');content.replaceChildren(renderPlan(pUpgrade));upgradeExec.disabled=false;}catch(e){err(e);}})();
  upgradeExec.onclick=()=>void(async()=>{if(!pUpgrade)return;upgradeExec.disabled=true;try{await api().releaseLifecycleUpgradeExecute(pUpgrade.plan_id,pUpgrade.plan_hash);rollbackPlan.disabled=false;await load();}catch(e){err(e);upgradeExec.disabled=false;}})();
  rollbackPlan.onclick=()=>void(async()=>{try{const r=await api().releaseLifecycleRollbackPlan();pRollback=r.data?.plan??null;if(!pRollback)throw new Error('RollbackPlan ausente.');content.replaceChildren(renderPlan(pRollback));rollbackExec.disabled=false;}catch(e){err(e);}})();
  rollbackExec.onclick=()=>void(async()=>{if(!pRollback)return;rollbackExec.disabled=true;try{await api().releaseLifecycleRollbackExecute(pRollback.plan_id,pRollback.plan_hash);await load();}catch(e){err(e);rollbackExec.disabled=false;}})();
  refresh.onclick=()=>void load();void load();return section;
}
