import { DevPilotApiClient, DevPilotApiError } from '../api/client';
import type { ReleaseApproval, ReleaseMetadataStatus, ReleaseTagPlan } from '../api/types';

function panel(title:string,text:string):HTMLElement{const a=document.createElement('article');a.className='panel';const h=document.createElement('h3');h.textContent=title;const p=document.createElement('p');p.textContent=text;a.append(h,p);return a;}
function fact(label:string,value:unknown):HTMLElement{const r=document.createElement('div');r.className='release-metadata-fact';const k=document.createElement('strong');k.textContent=label;const v=document.createElement('span');v.textContent=String(value??'—');r.append(k,v);return r;}
function renderStatus(data:ReleaseMetadataStatus):HTMLElement{const w=document.createElement('div');w.className='release-metadata-result';const p=panel('Version, release notes, approval and tag',`Estado actual: ${data.state}.`);const d=data.version_decision;const a=data.release_approval;const t=data.tag_verification as any;const f=document.createElement('div');f.className='release-metadata-facts';f.append(fact('Version',d?.version),fact('Tag',d?.tag_name),fact('Version policy',d?.status??'PENDING'),fact('Approval',a?.status??'PENDING'),fact('Tag exact commit',t?.exact_commit_match===true?'PASS':t?.exact_commit_match===false?'BLOCK':'—'),fact('Annotated tag',t?.annotated===true?'PASS':t?.annotated===false?'BLOCK':'—'),fact('Push/publication',t?.push_performed===false&&t?.publish_performed===false?'NONE':'—'));p.append(f);const b=panel('Authority boundary','Manual or agent-assisted text is proposal-only. Release approval is server-side and limited to owner/release-manager. Tagging is local annotated only; push, publish and deploy remain disabled.');w.append(p,b);return w;}

export function renderReleaseMetadataView(tokenProvider:()=>string|null):HTMLElement{
  const section=document.createElement('section');section.className='release-metadata-view';section.dataset.uiRouteId='ui.release-metadata';
  const intro=document.createElement('div');const h=document.createElement('h2');h.textContent='Version, release notes, tag and approval';const p=document.createElement('p');p.textContent='Prepare traceable release notes, verify version alignment, build an exact TagPlan, approve it as a human release authority, then create one local annotated tag.';intro.append(h,p);
  const form=document.createElement('div');form.className='release-metadata-form';
  const mode=document.createElement('select');for(const m of ['MANUAL','AGENT_ASSISTED']){const o=document.createElement('option');o.value=m;o.textContent=m;mode.append(o);}const version=document.createElement('input');version.value='0.1.1';version.setAttribute('aria-label','Release version');const notes=document.createElement('textarea');notes.rows=5;notes.placeholder='Optional editorial notes or agent proposal. They never carry approval authority.';
  const prepare=document.createElement('button');prepare.textContent='1. Preparar metadata + notes';const tagPlanBtn=document.createElement('button');tagPlanBtn.textContent='2. Crear TagPlan dry-run';tagPlanBtn.disabled=true;const approve=document.createElement('button');approve.textContent='3. Aprobar release';approve.disabled=true;const execute=document.createElement('button');execute.textContent='4. Crear annotated tag local';execute.disabled=true;const refresh=document.createElement('button');refresh.textContent='Actualizar estado';form.append(mode,version,notes,prepare,tagPlanBtn,approve,execute,refresh);section.append(intro,form);
  const content=document.createElement('div');content.className='release-metadata-content';section.append(content);const api=()=>new DevPilotApiClient({token:tokenProvider()});let plan:ReleaseTagPlan|null=null;let approval:ReleaseApproval|null=null;
  const err=(e:unknown)=>{const x=panel('Operación bloqueada',e instanceof DevPilotApiError?e.message:e instanceof Error?e.message:String(e));x.append(panel('Siguiente acción','No fuerce ni mueva tags. Corrija la precondición y repita solamente la fase pendiente.'));content.replaceChildren(x);};
  const load=async()=>{try{const r=await api().releaseMetadataStatus();content.replaceChildren(renderStatus(r.data));plan=r.data.tag_plan??null;approval=r.data.release_approval??null;tagPlanBtn.disabled=!r.data.version_decision;approve.disabled=!plan;execute.disabled=!plan||!approval;}catch(e){err(e);}};
  prepare.onclick=()=>void(async()=>{prepare.disabled=true;try{const m=mode.value as 'MANUAL'|'AGENT_ASSISTED';await api().releaseMetadataPrepare({mode:m,version:version.value.trim(),manual_notes:m==='MANUAL'?notes.value:'',agent_proposal:m==='AGENT_ASSISTED'?notes.value:''});await load();}catch(e){err(e);}finally{prepare.disabled=false;}})();
  tagPlanBtn.onclick=()=>void(async()=>{tagPlanBtn.disabled=true;try{const r=await api().releaseMetadataTagPlan();plan=r.data.tag_plan;approve.disabled=false;await load();}catch(e){err(e);tagPlanBtn.disabled=false;}})();
  approve.onclick=()=>void(async()=>{if(!plan)return;approve.disabled=true;try{const r=await api().releaseMetadataApprove(plan.plan_id,plan.plan_hash,'Reviewed version, provenance and exact local TagPlan.');approval=r.data.release_approval;execute.disabled=false;await load();}catch(e){err(e);approve.disabled=false;}})();
  execute.onclick=()=>void(async()=>{if(!plan||!approval)return;execute.disabled=true;try{await api().releaseMetadataTagExecute(plan.plan_id,plan.plan_hash,approval.approval_id);await load();}catch(e){err(e);execute.disabled=false;}})();
  refresh.onclick=()=>void load();void load();return section;
}
