import { armApprovalCenterArtifactReviewHandoff, DevPilotApiClient, DevPilotApiError } from '../api/client';
import type { AuthSessionContext, GovernedJobSnapshot } from '../api/types';

type SourceRow = { source_id:string; relative_path:string; name:string; extension:string; size_bytes:number; language_hint:string };
type SourceData = { source_id:string; relative_path:string; content:string; sha256:string; language_hint:string };
type Draft = { draft_id:string; operation:'CREATE'|'EDIT'|'RENAME'; target_path:string; status:'DRAFT'|'CONFLICT'; revision_sha256:string; source?:{source_id?:string;relative_path?:string;sha256?:string}; safety?:Record<string,unknown> };
type ChangePlan = { plan_id:string; plan_hash:string; full_diff:string; exact_path_allowlist:string[]; required_approval_role:string; risk:{level:string;reasons:string[]}; test_impact_preview:Record<string,unknown>; changes:Array<Record<string,unknown>> };
type Execution = { execution_id:string; status:string; plan_id:string; plan_hash:string; approval_id:string; changes:Array<Record<string,unknown>> };
type AgentProposal = { proposal_id:string; proposal_sha256:string; agent_type:'coding'|'test'; status:string; target_path:string; operation:'EDIT'|'CREATE'; proposed_content:string; full_diff:string; model_id:string; provider_id:string; access_route_id:string; agent_session:string; trace_id:string; tool_intent:Record<string,unknown>; tool_execution_decision:Record<string,unknown>; cost:Record<string,unknown>; provenance:Record<string,unknown>; safety:Record<string,unknown> };
type StoryTestPlan = { test_plan_id:string; test_plan_hash:string; status:string; story_execution_id:string; story_id:string; story_version?:string; source_change_plan_id:string; source_change_plan_hash:string; changed_paths:string[]; test_impact_report_hash:string; matched_contracts:Array<Record<string,unknown>>; matched_rules:Array<Record<string,unknown>>; required_tests:string[]; recommended_tests:string[]; effective_required_tests:string[]; test_reasons:Record<string,string[]>; test_policy:Record<string,{criticality:string;waivable:boolean;reason:string}>; unknown_impact:{paths:string[];manual_review_required:boolean;fail_closed:boolean}; sensitive_impact:{paths:string[];present:boolean;under_testing_blocked?:boolean}; full_regression_signal:{required_before_backlog_or_release_closure:boolean;informational_only:boolean;execution_authorized:boolean;profile_id?:string}; review?:Record<string,unknown>; active_waivers?:Array<Record<string,unknown>>; expired_waivers?:Array<Record<string,unknown>> };

const APPLY_CONTEXT_SESSION_KEY='devpilot.story-code.apply-context.v1';

export function renderStoryCodeWorkbenchView(tokenProvider:()=>string|null, session:AuthSessionContext):HTMLElement {
  const host=document.createElement('section'); host.className='story-code-workbench'; host.dataset.routeId='ui.story-code-workbench'; host.dataset.gsdlc09c='governed-source-change'; host.dataset.gsdlc09d='proposal-only-agent-assist'; host.dataset.gsdlc10a='story-test-plan'; host.dataset.gsdlc10b='story-validation-jobs';
  const intro=panel('Story Code Workbench','Autoría manual bounded + asistencia proposal-only + SourceChangePlan gobernado + StoryTestPlan UI-native. Después de apply, Validar deriva Test Impact v2 y un plan de pruebas explicable; no ejecuta comandos ni Full Regression.');
  const safety=document.createElement('div'); safety.className='code-safety-strip'; safety.dataset.sourceWrite='approval-gated'; safety.textContent='SOURCE WRITE · APPROVAL-GATED · EXACT PATH ALLOWLIST · ATOMIC APPLY/ROLLBACK · SIN TERMINAL'; intro.append(safety); host.append(intro);
  const state=document.createElement('div'); state.className='notice'; state.setAttribute('role','status'); state.setAttribute('aria-live','polite'); host.append(state);
  const layout=document.createElement('div'); layout.className='code-workbench-grid';
  const sourcePanel=panel('Source tree','Solo archivos de texto/código admitidos por la policy server-side.');
  const sourceList=document.createElement('div'); sourceList.className='code-source-list'; sourceList.dataset.sourceList='true'; sourcePanel.append(sourceList);
  const editorPanel=panel('Editor de draft','El editor persiste SourceDraftBuffer runtime-only. Source no cambia hasta apply aprobado.');
  const sourceMeta=document.createElement('p'); sourceMeta.className='muted'; sourceMeta.dataset.sourceMeta='true'; sourceMeta.textContent='Selecciona un archivo o usa CREATE.';
  const mode=document.createElement('select'); mode.setAttribute('aria-label','Operación de draft'); for(const value of ['EDIT','CREATE','RENAME']){const o=document.createElement('option');o.value=value;o.textContent=value;mode.append(o);}
  const target=document.createElement('input'); target.type='text'; target.placeholder='src/module.py'; target.setAttribute('aria-label','Ruta destino'); target.dataset.targetPath='true';
  const editor=document.createElement('textarea'); editor.rows=22; editor.spellcheck=false; editor.setAttribute('aria-label','Contenido del draft'); editor.dataset.draftEditor='true';
  const actions=document.createElement('div'); actions.className='code-workbench-actions';
  const save=button('Guardar draft'); save.dataset.saveDraft='true';
  const recheck=button('Revalidar preimage'); recheck.dataset.recheckDraft='true';
  const discard=button('Descartar draft'); discard.dataset.discardDraft='true';
  const sourceHash=document.createElement('code'); sourceHash.dataset.sourceHash='true';
  const draftInfo=document.createElement('div'); draftInfo.className='code-draft-status'; draftInfo.dataset.draftStatus='true';
  actions.append(save,recheck,discard); editorPanel.append(sourceMeta,mode,target,editor,actions,sourceHash,draftInfo);
  layout.append(sourcePanel,editorPanel); host.append(layout);

  const agentPanel=panel('Agent assistance · proposal-only','CodingAgent y TestAgent usan StoryContextPack + RAG + Model Gateway mock/local. Una propuesta nunca escribe source, no crea draft, no aprueba ni hace commit.'); agentPanel.dataset.agentAssistPanel='true';
  const agentControls=document.createElement('div'); agentControls.className='code-workbench-actions';
  const agentType=document.createElement('select'); agentType.setAttribute('aria-label','Tipo de agente'); agentType.dataset.agentType='true'; for(const [value,label] of [['coding','CodingAgent'],['test','TestAgent']]){const o=document.createElement('option');o.value=value;o.textContent=label;agentType.append(o);}
  const agentMode=document.createElement('select'); agentMode.setAttribute('aria-label','Ruta de modelo'); agentMode.dataset.agentMode='true'; for(const value of ['mock','fake-local']){const o=document.createElement('option');o.value=value;o.textContent=value;agentMode.append(o);}
  const agentInstruction=document.createElement('textarea'); agentInstruction.rows=3; agentInstruction.maxLength=2000; agentInstruction.placeholder='Describe la propuesta que deseas revisar. No incluyas secretos ni acciones destructivas.'; agentInstruction.setAttribute('aria-label','Instrucción para propuesta agentic'); agentInstruction.dataset.agentInstruction='true';
  const generateProposal=button('Generar propuesta'); generateProposal.dataset.generateAgentProposal='true';
  const acceptProposal=button('Aceptar en editor'); acceptProposal.dataset.acceptAgentProposal='true'; acceptProposal.disabled=true;
  const rejectProposal=button('Rechazar propuesta'); rejectProposal.dataset.rejectAgentProposal='true'; rejectProposal.disabled=true;
  agentControls.append(agentType,agentMode,generateProposal,acceptProposal,rejectProposal);
  const agentStatus=document.createElement('div'); agentStatus.className='code-draft-status'; agentStatus.dataset.agentProposalStatus='true';
  const agentDiff=document.createElement('pre'); agentDiff.className='code-full-diff'; agentDiff.dataset.agentProposalDiff='true'; agentDiff.textContent='Genera una propuesta para revisar su diff sin mutar draft/source.';
  const agentProvenance=document.createElement('pre'); agentProvenance.className='code-test-impact'; agentProvenance.dataset.agentProvenance='true';
  const agentSafety=document.createElement('pre'); agentSafety.className='code-change-evidence'; agentSafety.dataset.agentToolDecision='true';
  agentPanel.append(agentInstruction,agentControls,agentStatus,agentDiff,agentProvenance,agentSafety); host.append(agentPanel);

  const changePanel=panel('Governed source change','Secuencia obligatoria: immutable plan → diff/Test Impact → recheck/dry-run → owner approval → atomic apply → separate rollback approval.'); changePanel.dataset.changePlanPanel='true';
  const planActions=document.createElement('div'); planActions.className='code-workbench-actions';
  const createPlan=button('Crear SourceChangePlan'); createPlan.dataset.createChangePlan='true';
  const planRecheck=button('Revalidar plan'); planRecheck.dataset.recheckChangePlan='true';
  const dryRun=button('Dry-run'); dryRun.dataset.dryRunChangePlan='true';
  const requestApproval=button('Solicitar approval owner'); requestApproval.dataset.requestApplyApproval='true';
  const approvalLink=document.createElement('a'); approvalLink.href='/approvals'; approvalLink.target='_blank'; approvalLink.rel='noopener'; approvalLink.textContent='Abrir Approval Center dirigido ↗'; approvalLink.hidden=true;
  const approvalInput=document.createElement('input'); approvalInput.type='text'; approvalInput.placeholder='Approval ID aprobado'; approvalInput.setAttribute('aria-label','Approval ID de apply'); approvalInput.dataset.applyApprovalId='true';
  const apply=button('Aplicar plan aprobado'); apply.dataset.applyChangePlan='true';
  planActions.append(createPlan,planRecheck,dryRun,requestApproval,approvalLink,approvalInput,apply);
  const planMeta=document.createElement('div'); planMeta.className='code-draft-status'; planMeta.dataset.changePlanMeta='true';
  const diff=document.createElement('pre'); diff.className='code-full-diff'; diff.dataset.fullDiff='true'; diff.textContent='Crea un draft y luego el SourceChangePlan para ver el diff completo.';
  const impact=document.createElement('pre'); impact.className='code-test-impact'; impact.dataset.testImpact='true';
  changePanel.append(planActions,planMeta,diff,impact); host.append(changePanel);

  const validationPanel=panel('Validar · Test Impact y StoryTestPlan','Journey 10-A: Story CHANGES_READY → Validar → Test Impact v2 → review/approval. El plan explica required/recommended, escala unknown/sensitive y nunca ejecuta comandos ni Full Regression.'); validationPanel.dataset.storyTestPlanPanel='true';
  const validationActions=document.createElement('div'); validationActions.className='code-workbench-actions';
  const validateStory=button('Validar story'); validateStory.dataset.validateStory='true';
  const approveTestPlan=button('Aprobar StoryTestPlan'); approveTestPlan.dataset.approveStoryTestPlan='true';
  const rejectTestPlan=button('Rechazar StoryTestPlan'); rejectTestPlan.dataset.rejectStoryTestPlan='true';
  const waiverReason=document.createElement('input'); waiverReason.type='text'; waiverReason.maxLength=500; waiverReason.placeholder='Razón obligatoria para waiver owner'; waiverReason.setAttribute('aria-label','Razón de waiver del StoryTestPlan'); waiverReason.dataset.testPlanWaiverReason='true';
  const waiveTestPlan=button('Waiver owner'); waiveTestPlan.dataset.waiveStoryTestPlan='true';
  validationActions.append(validateStory,approveTestPlan,rejectTestPlan,waiverReason,waiveTestPlan);
  const testPlanMeta=document.createElement('div'); testPlanMeta.className='code-draft-status'; testPlanMeta.dataset.storyTestPlanMeta='true'; testPlanMeta.textContent='Aplica un SourceChangePlan y luego pulsa Validar.';
  const impactAlerts=document.createElement('div'); impactAlerts.className='story-test-plan-alerts'; impactAlerts.dataset.storyTestPlanAlerts='true';
  const testPlanGrid=document.createElement('div'); testPlanGrid.className='story-test-plan-grid';
  const requiredCard=document.createElement('section'); requiredCard.className='viewer-card'; const requiredTitle=document.createElement('h4'); requiredTitle.textContent='Required tests'; const requiredList=document.createElement('ul'); requiredList.className='story-test-plan-list'; requiredList.dataset.requiredTests='true'; requiredCard.append(requiredTitle,requiredList);
  const recommendedCard=document.createElement('section'); recommendedCard.className='viewer-card'; const recommendedTitle=document.createElement('h4'); recommendedTitle.textContent='Recommended tests'; const recommendedList=document.createElement('ul'); recommendedList.className='story-test-plan-list'; recommendedList.dataset.recommendedTests='true'; recommendedCard.append(recommendedTitle,recommendedList);
  testPlanGrid.append(requiredCard,recommendedCard);
  const fullSignal=document.createElement('div'); fullSignal.className='code-safety-strip'; fullSignal.dataset.fullRegressionSignal='true'; fullSignal.textContent='FULL REGRESSION · informative only · execution_authorized=false · budget 10-A=0';
  validationPanel.append(validationActions,testPlanMeta,impactAlerts,testPlanGrid,fullSignal); host.append(validationPanel);

  const jobsPanel=panel('Ejecutar validaciones · jobs gobernados','Journey 10-B: StoryTestPlan APPROVED → jobs tipados test/build/lint → Job Console con lifecycle, heartbeat y logs sanitizados. No acepta comandos libres ni inicia Full Regression.'); jobsPanel.dataset.storyValidationJobsPanel='true';
  const jobsActions=document.createElement('div'); jobsActions.className='code-workbench-actions';
  const planValidationJobs=button('Planificar jobs tipados'); planValidationJobs.dataset.planValidationJobs='true';
  const refreshValidationJobs=button('Actualizar jobs'); refreshValidationJobs.dataset.refreshValidationJobs='true';
  jobsActions.append(planValidationJobs,refreshValidationJobs);
  const jobsMeta=document.createElement('div'); jobsMeta.className='code-draft-status'; jobsMeta.dataset.storyValidationJobsMeta='true'; jobsMeta.textContent='Aprueba el StoryTestPlan para habilitar jobs test/build/lint allowlisted.';
  const jobsList=document.createElement('div'); jobsList.className='viewer-list story-validation-jobs'; jobsList.dataset.storyValidationJobsList='true';
  const jobsSafety=document.createElement('div'); jobsSafety.className='code-safety-strip'; jobsSafety.textContent='TYPED JOBS ONLY · NO ARBITRARY SHELL · BOUNDED LOGS · FULL REGRESSION=0 EN 10-B';
  jobsPanel.append(jobsActions,jobsMeta,jobsList,jobsSafety); host.append(jobsPanel);

  const rollbackPanel=panel('Apply manifest y rollback','Rollback es una operación gobernada separada; nunca reutiliza el approval de apply.'); rollbackPanel.dataset.rollbackPanel='true';
  const rollbackActions=document.createElement('div'); rollbackActions.className='code-workbench-actions';
  const requestRollback=button('Solicitar approval de rollback'); requestRollback.dataset.requestRollbackApproval='true';
  const rollbackLink=document.createElement('a'); rollbackLink.href='/approvals'; rollbackLink.target='_blank'; rollbackLink.rel='noopener'; rollbackLink.textContent='Abrir Approval Center ↗'; rollbackLink.hidden=true;
  const rollbackInput=document.createElement('input'); rollbackInput.type='text'; rollbackInput.placeholder='Approval ID de rollback aprobado'; rollbackInput.setAttribute('aria-label','Approval ID de rollback'); rollbackInput.dataset.rollbackApprovalId='true';
  const rollback=button('Ejecutar rollback aprobado'); rollback.dataset.executeRollback='true';
  const evidence=document.createElement('pre'); evidence.className='code-change-evidence'; evidence.dataset.changeEvidence='true';
  rollbackActions.append(requestRollback,rollbackLink,rollbackInput,rollback); rollbackPanel.append(rollbackActions,evidence); host.append(rollbackPanel);

  const client=()=>new DevPilotApiClient({token:tokenProvider()});
  let selected:SourceData|null=null; let draft:Draft|null=null; let plan:ChangePlan|null=null; let execution:Execution|null=null; let agentProposal:AgentProposal|null=null; let storyTestPlan:StoryTestPlan|null=null; let validationJobs:GovernedJobSnapshot[]=[];
  let storyStatus='UNKNOWN';
  const canAuthor=session.principal.roles.some((x)=>['owner','developer'].includes(x)); const isOwner=session.principal.roles.includes('owner');
  save.disabled=!canAuthor; createPlan.disabled=true; planRecheck.disabled=true; dryRun.disabled=true; requestApproval.disabled=true; apply.disabled=true; requestRollback.disabled=true; rollback.disabled=true; validateStory.disabled=true; approveTestPlan.disabled=true; rejectTestPlan.disabled=true; waiveTestPlan.disabled=true; planValidationJobs.disabled=true; refreshValidationJobs.disabled=true;
  if(!canAuthor)save.title='Solo owner/developer puede persistir SourceDraftBuffer.'; if(!isOwner){requestApproval.title='Solo owner puede solicitar/aplicar.';apply.title=requestApproval.title;requestRollback.title=requestApproval.title;rollback.title=requestApproval.title;approveTestPlan.title='Solo owner puede aprobar StoryTestPlan.';waiveTestPlan.title='Solo owner puede crear waivers.';}

  mode.addEventListener('change',()=>{const op=mode.value;if(op==='CREATE'){selected=null;target.value='src/new_file.py';editor.value='';sourceMeta.textContent='CREATE · archivo nuevo como draft runtime-only.';}else if(selected){target.value=selected.relative_path;editor.value=selected.content;} updateButtons();});
  save.addEventListener('click',()=>void saveDraft()); recheck.addEventListener('click',()=>void recheckDraft()); discard.addEventListener('click',()=>void discardDraft());
  generateProposal.addEventListener('click',()=>void createAgentProposal()); acceptProposal.addEventListener('click',()=>void decideAgentProposal('ACCEPT')); rejectProposal.addEventListener('click',()=>void decideAgentProposal('REJECT'));
  agentType.addEventListener('change',()=>{if(agentType.value==='coding'&&!selected)agentStatus.textContent='CodingAgent requiere un source seleccionado; TestAgent puede proponer un archivo de test nuevo.';});
  createPlan.addEventListener('click',()=>void createChangePlan()); planRecheck.addEventListener('click',()=>void recheckPlan()); dryRun.addEventListener('click',()=>void runDryRun()); requestApproval.addEventListener('click',()=>void requestApplyApproval()); apply.addEventListener('click',()=>void executeApply()); validateStory.addEventListener('click',()=>void createStoryTestPlan()); approveTestPlan.addEventListener('click',()=>void decideStoryTestPlan('APPROVE')); rejectTestPlan.addEventListener('click',()=>void decideStoryTestPlan('REJECT')); waiveTestPlan.addEventListener('click',()=>void waiveStoryTestPlanRequest()); waiverReason.addEventListener('input',updateButtons); requestRollback.addEventListener('click',()=>void requestRollbackApproval()); rollback.addEventListener('click',()=>void executeRollback());
  planValidationJobs.addEventListener('click',()=>void createStoryValidationJobs()); refreshValidationJobs.addEventListener('click',()=>void loadStoryValidationJobs());
  void refresh();

  async function refresh(options:{preserveNotice?:boolean}={}):Promise<void>{
    const preserveNotice=options.preserveNotice===true;
    if(!preserveNotice)setState('loading','Cargando story/context y source tree…');
    try{
      const [status,sources]=await Promise.all([client().storyCodeStatus(),client().storyCodeSources()]);
      const story=((status.data as any).story??{});
      storyStatus=String(story.status??'UNKNOWN').toUpperCase();
      sourceMeta.textContent=`Story ${String(story.story_id??'sin story')} · ${storyStatus} · source write=approval-gated`;
      renderSources(((sources.data as any).sources??[]) as SourceRow[]);
      const restored=!plan ? await restoreApplyContext(story) : {restored:false,approvalUsable:false};
      updateButtons();
      if(!preserveNotice){
        if(restored.restored&&storyStatus==='CHANGES_READY')setState('pass','PASS · SourceChangePlan restaurado para validación; Story CHANGES_READY; Validar story habilitado.');
        else if(restored.restored)setState('pass',restored.approvalUsable?'PASS · SourceChangePlan y approval owner restaurados desde autoridad server-side.':'PASS · SourceChangePlan restaurado desde autoridad server-side; solicite un approval owner nuevo antes de aplicar.');
        else setState('pass',`PASS · ${((sources.data as any).summary?.sources_total??0)} fuentes allowlisted.`);
      }
    }catch(e){
      setState('block',errorText(e));
      if(preserveNotice)throw e;
    }
  }
  function renderSources(rows:SourceRow[]):void{sourceList.replaceChildren();if(!rows.length){const p=document.createElement('p');p.className='muted';p.textContent='No hay source allowlisted.';sourceList.append(p);return;}for(const row of rows){const b=button(`${row.relative_path} · ${row.language_hint}`);b.className='code-source-item';b.dataset.sourcePath=row.relative_path;b.addEventListener('click',()=>void openSource(row));sourceList.append(b);}}
  async function openSource(row:SourceRow):Promise<void>{setState('loading',`Leyendo ${row.relative_path}…`);try{const r=await client().storyCodeSource(row.source_id);selected=(r.data as any).source as SourceData;mode.value='EDIT';target.value=selected.relative_path;editor.value=selected.content;sourceMeta.textContent=`${selected.relative_path} · ${selected.language_hint}`;sourceHash.textContent=`preimage ${selected.sha256}`;draft=null;clearPlan();draftInfo.textContent='';recheck.disabled=true;discard.disabled=true;updateButtons();setState('pass','PASS · source leído por opaque id.');}catch(e){setState('block',errorText(e));}}
  async function createAgentProposal():Promise<void>{
    if(!canAuthor){setState('block','BLOCK · owner/developer requerido para solicitar propuestas.');return;}
    const kind=agentType.value as 'coding'|'test';
    if(kind==='coding'&&!selected){setState('block','BLOCK · CodingAgent requiere source seleccionado.');return;}
    const instruction=agentInstruction.value.trim(); if(!instruction){setState('block','BLOCK · escribe una instrucción acotada.');return;}
    setState('loading',`Solicitando ${kind==='coding'?'CodingAgent':'TestAgent'} proposal-only por ${agentMode.value}…`);
    try{const r=await client().storyAgentProposalCreate({agent_type:kind,mode:agentMode.value as 'mock'|'fake-local',instruction,source_id:kind==='coding'?(selected?.source_id??null):null});agentProposal=(r.data as any).proposal as AgentProposal;renderAgentProposal();setState('pass','PASS · propuesta agentic creada; source/draft mutations=false.');}
    catch(e){agentProposal=null;renderAgentProposal();setState('block',errorText(e));}
  }
  async function decideAgentProposal(decision:'ACCEPT'|'REJECT'):Promise<void>{
    if(!agentProposal)return; setState('loading',`${decision==='ACCEPT'?'Aceptando para revisión humana en editor':'Rechazando'} propuesta…`);
    try{const r=await client().storyAgentProposalDecision(agentProposal.proposal_id,agentProposal.proposal_sha256,decision);agentProposal=(r.data as any).proposal as AgentProposal;
      if(decision==='ACCEPT'){const proposal=agentProposal; editor.value=proposal.proposed_content; target.value=proposal.target_path; if(proposal.operation==='CREATE'){mode.value='CREATE'; selected=null;} else {mode.value='EDIT';} draft=null; clearPlan(); draftInfo.textContent='Proposal ACCEPTED → contenido insertado en editor solamente; presiona Guardar draft para persistir SourceDraftBuffer.'; setState('pass','PASS · aceptación humana insertó contenido en editor; source/draft write=false.');}
      else {setState('pass','PASS · propuesta rechazada; source/draft write=false.');}
      renderAgentProposal(); updateButtons();
    }catch(e){setState('block',errorText(e));}
  }
  function renderAgentProposal():void{
    if(!agentProposal){agentStatus.textContent='';agentDiff.textContent='Genera una propuesta para revisar su diff sin mutar draft/source.';agentProvenance.textContent='';agentSafety.textContent='';acceptProposal.disabled=true;rejectProposal.disabled=true;return;}
    agentStatus.textContent=`${agentProposal.agent_type==='coding'?'CodingAgent':'TestAgent'} · ${agentProposal.status} · ${agentProposal.proposal_id} · target=${agentProposal.target_path}`;
    agentDiff.textContent=agentProposal.full_diff||'(diff vacío)';
    agentProvenance.textContent=JSON.stringify({model_id:agentProposal.model_id,provider_id:agentProposal.provider_id,access_route_id:agentProposal.access_route_id,agent_session:agentProposal.agent_session,trace_id:agentProposal.trace_id,cost:agentProposal.cost,provenance:agentProposal.provenance},null,2);
    agentSafety.textContent=JSON.stringify({ToolIntent:agentProposal.tool_intent,ToolExecutionDecision:agentProposal.tool_execution_decision,safety:agentProposal.safety},null,2);
    const pending=agentProposal.status==='PROPOSED';acceptProposal.disabled=!pending;rejectProposal.disabled=!pending;
  }
  async function saveDraft():Promise<void>{if(!canAuthor){setState('block','BLOCK · rol read-only.');return;}const operation=mode.value as 'CREATE'|'EDIT'|'RENAME';if(operation!=='CREATE'&&!selected){setState('block','BLOCK · selecciona source para EDIT/RENAME.');return;}setState('loading','Guardando SourceDraftBuffer runtime-only…');try{const r=await client().storyCodeDraftSave({operation,content:editor.value,target_path:target.value,source_id:selected?.source_id??null,expected_source_sha256:selected?.sha256??null,expected_revision_sha256:draft?.revision_sha256??null});draft=(r.data as any).draft as Draft;clearPlan();renderDraft();setState('pass','PASS · draft guardado; source real permanece sin cambios.');}catch(e){setState('block',errorText(e));}}
  async function recheckDraft():Promise<void>{if(!draft)return;setState('loading','Revalidando source preimage…');try{const r=await client().storyCodeDraftRecheck(draft.draft_id);draft=(r.data as any).draft as Draft;renderDraft();setState('pass','PASS · preimage vigente.');}catch(e){setState('block',errorText(e));draftInfo.textContent='CONFLICT · external edit/revalidation requerida';draftInfo.dataset.conflict='true';clearPlan();}}
  async function discardDraft():Promise<void>{if(!draft)return;try{await client().storyCodeDraftDiscard(draft.draft_id,draft.revision_sha256);draft=null;clearPlan();draftInfo.textContent='Draft descartado; source no fue modificado.';recheck.disabled=true;discard.disabled=true;updateButtons();setState('pass','PASS · runtime draft descartado.');}catch(e){setState('block',errorText(e));}}
  async function createChangePlan():Promise<void>{if(!draft)return;setState('loading','Construyendo plan inmutable y Test Impact preview…');try{const r=await client().storySourceChangePlanCreate([draft.draft_id]);plan=(r.data as any).plan as ChangePlan;renderPlan();setState('pass','PASS · SourceChangePlan inmutable creado; no hubo source write.');}catch(e){setState('block',errorText(e));}}
  async function recheckPlan():Promise<void>{if(!plan)return;setState('loading','Revalidando preimages exactos…');try{await client().storySourceChangePlanRecheck(plan.plan_id,plan.plan_hash);setState('pass','PASS · plan/preimages vigentes.');}catch(e){setState('block',errorText(e));}}
  async function runDryRun():Promise<void>{if(!plan)return;setState('loading','Ejecutando dry-run gobernado…');try{const r=await client().storySourceChangeDryRun(plan.plan_id,plan.plan_hash);evidence.textContent=JSON.stringify(r.data,null,2);setState('pass','PASS · dry-run sin mutación de source.');}catch(e){setState('block',errorText(e));}}
  async function requestApplyApproval():Promise<void>{if(!plan||!isOwner)return;setState('loading','Solicitando approval owner exacto…');try{const r=await client().storySourceChangeApplyApprovalRequest(plan.plan_id,plan.plan_hash);const id=String((r.data as any)?.approval?.approval_id??(r.data as any)?.approval_id??'');if(!id)throw new Error('La API no devolvió Approval ID.');approvalInput.value=id;armApprovalCenterArtifactReviewHandoff(session,id);approvalLink.href=`/approvals?handoff=artifact-review&approval_id=${encodeURIComponent(id)}`;approvalLink.hidden=false;persistApplyContext(plan,id);apply.disabled=false;setState('pass',`PENDING · approval ${id} creado; abre el Approval Center dirigido y decide exactamente este ID con sesión humana owner.`);}catch(e){setState('block',errorText(e));}}
  async function executeApply():Promise<void>{if(!plan||!isOwner)return;const id=approvalInput.value.trim();if(!id){setState('block','BLOCK · ingresa el Approval ID aprobado.');return;}setState('loading','Revalidando preimage y ejecutando apply all-or-nothing…');try{const r=await client().storySourceChangeApply(plan.plan_id,plan.plan_hash,id);execution=(r.data as any).execution as Execution;evidence.textContent=JSON.stringify((r.data as any).apply_manifest??r.data,null,2);requestRollback.disabled=false;clearPersistedApplyContext();updateButtons();await refresh({preserveNotice:true});setState('pass','PASS · apply exacto verificado; manifest disponible.');}catch(e){setState('block',errorText(e));}}
  async function createStoryTestPlan():Promise<void>{if(!plan||storyStatus!=='CHANGES_READY'){setState('block',`BLOCK · Validar requiere SourceChangePlan restaurado y Story CHANGES_READY; current=${storyStatus}.`);return;}setState('loading','Derivando Test Impact v2 y StoryTestPlan hash-bound…');try{const r=await client().storyTestPlanCreate(plan.plan_id,plan.plan_hash);storyTestPlan=(r.data as any).story_test_plan as StoryTestPlan;renderStoryTestPlan();setState('pass','PASS · StoryTestPlan derivado; required/recommended explicables; test execution=false.');}catch(e){setState('block',errorText(e));}}
  async function decideStoryTestPlan(decision:'APPROVE'|'REJECT'):Promise<void>{if(!storyTestPlan)return;if(decision==='APPROVE'&&!isOwner){setState('block','BLOCK · solo owner puede aprobar StoryTestPlan.');return;}if(decision==='REJECT'&&!canAuthor){setState('block','BLOCK · owner/developer requerido.');return;}setState('loading',`${decision==='APPROVE'?'Aprobando':'Rechazando'} StoryTestPlan por autoridad humana…`);try{const r=await client().storyTestPlanDecision(storyTestPlan.test_plan_id,{test_plan_hash:storyTestPlan.test_plan_hash,decision,reason:decision==='REJECT'?'Revisión humana rechazó el plan.':'Revisión humana owner aprobó el plan.'});storyTestPlan=(r.data as any).story_test_plan as StoryTestPlan;renderStoryTestPlan();setState('pass',`PASS · StoryTestPlan ${decision}.`);}catch(e){setState('block',errorText(e));}}
  async function createStoryValidationJobs():Promise<void>{if(!storyTestPlan||storyTestPlan.status!=='APPROVED'){setState('block','BLOCK · StoryValidationJobs requieren StoryTestPlan APPROVED.');return;}setState('loading','Planificando jobs tipados desde StoryTestPlan aprobado…');try{const r=await client().createStoryValidationJobs(storyTestPlan.test_plan_id,storyTestPlan.test_plan_hash);validationJobs=((r.data as any)?.jobs??[]) as GovernedJobSnapshot[];renderValidationJobs();setState('pass',`PASS · ${validationJobs.length} job(s) tipados planificados; Full=0.`);}catch(e){setState('block',errorText(e));}}
  async function loadStoryValidationJobs():Promise<void>{if(!storyTestPlan)return;try{const r=await client().listStoryValidationJobs(storyTestPlan.test_plan_id);validationJobs=((r.data as any)?.jobs??[]) as GovernedJobSnapshot[];renderValidationJobs();}catch(e){setState('block',errorText(e));}}
  async function startStoryValidationJob(job:GovernedJobSnapshot):Promise<void>{setState('loading',`Iniciando ${job.story_validation_kind??job.capability_id} como job tipado…`);try{await client().startStoryValidationJob(job.job_id);await loadStoryValidationJobs();setState('pass',`PASS · ${job.job_id} iniciado; observa lifecycle/logs en Job Console.`);}catch(e){setState('block',errorText(e));}}
  function renderValidationJobs():void{jobsList.replaceChildren();if(!validationJobs.length){jobsMeta.textContent='Sin jobs planificados para el StoryTestPlan actual.';updateButtons();return;}jobsMeta.textContent=`${validationJobs.length} job(s) · StoryTestPlan ${storyTestPlan?.test_plan_id??''} · lifecycle gobernado · Full=0`;for(const job of validationJobs){const row=document.createElement('div');row.className='viewer-list__item story-validation-job-row';const summary=document.createElement('span');summary.textContent=`${String(job.story_validation_status??job.status).toUpperCase()} · ${job.story_validation_kind??job.capability_id} · retry ${job.retry_count}/${job.retry_limit}`;const start=button('Iniciar');start.disabled=!['planned','approved','queued'].includes(job.status);start.addEventListener('click',()=>void startStoryValidationJob(job));const open=document.createElement('a');open.href=`/jobs/${encodeURIComponent(job.job_id)}`;open.textContent='Abrir Job Console';row.append(summary,start,open);jobsList.append(row);}updateButtons();}
  async function waiveStoryTestPlanRequest():Promise<void>{if(!storyTestPlan||!isOwner)return;const reason=waiverReason.value.trim();if(!reason){setState('block','BLOCK · waiver requiere razón explícita.');return;}const waived=storyTestPlan.effective_required_tests.filter((testId)=>storyTestPlan?.test_policy?.[testId]?.waivable===true);if(!waived.length){setState('block','BLOCK · no hay required tests waivable; sensitive/P0 permanecen obligatorios.');return;}setState('loading','Aplicando waiver owner con alcance y expiración…');try{const r=await client().storyTestPlanDecision(storyTestPlan.test_plan_id,{test_plan_hash:storyTestPlan.test_plan_hash,decision:'WAIVE',reason,waived_test_ids:waived,ttl_minutes:60});storyTestPlan=(r.data as any).story_test_plan as StoryTestPlan;waiverReason.value='';renderStoryTestPlan();setState('pass',`PASS · waiver owner aplicado a ${waived.length} test(s); expiry=60m.`);}catch(e){setState('block',errorText(e));}}
  function clearStoryTestPlan():void{storyTestPlan=null;validationJobs=[];jobsList.replaceChildren();jobsMeta.textContent='Aprueba el StoryTestPlan para habilitar jobs test/build/lint allowlisted.';testPlanMeta.textContent='Aplica un SourceChangePlan y luego pulsa Validar.';impactAlerts.replaceChildren();requiredList.replaceChildren();recommendedList.replaceChildren();fullSignal.textContent='FULL REGRESSION · informative only · execution_authorized=false · budget 10-A=0';waiverReason.value='';}
  function renderStoryTestPlan():void{if(!storyTestPlan){clearStoryTestPlan();updateButtons();return;}const p=storyTestPlan;testPlanMeta.textContent=`${p.test_plan_id} · hash ${p.test_plan_hash.slice(0,16)} · story=${p.story_id} · source-plan=${p.source_change_plan_id} · impact=${p.test_impact_report_hash.slice(0,16)} · status=${p.status}`;impactAlerts.replaceChildren();if(p.unknown_impact.paths.length){impactAlerts.append(alertLine('BLOCK/REVIEW · unknown impact',p.unknown_impact.paths.join(', '),'block'));}else{impactAlerts.append(alertLine('PASS · unknown impact','0 paths','pass'));}if(p.sensitive_impact.present){impactAlerts.append(alertLine('SENSITIVE · fail-closed',p.sensitive_impact.paths.join(', '),'block'));}else{impactAlerts.append(alertLine('PASS · sensitive impact','none','pass'));}requiredList.replaceChildren();for(const testId of p.required_tests){const reasons=(p.test_reasons?.[testId]??[]).join(' · ')||'Required by current Test Contract policy.';const policy=p.test_policy?.[testId];requiredList.append(testLine(testId,`${reasons} · ${policy?.criticality??'unknown'} · ${policy?.waivable?'waivable':'not waivable'}`));}if(!p.required_tests.length)requiredList.append(testLine('—','No required tests for this bounded delta.'));recommendedList.replaceChildren();for(const testId of p.recommended_tests){const reasons=(p.test_reasons?.[testId]??[]).join(' · ')||'Recommended by Test Impact v2.';recommendedList.append(testLine(testId,reasons));}if(!p.recommended_tests.length)recommendedList.append(testLine('—','No additional recommended tests.'));fullSignal.textContent=`FULL REGRESSION · informative only · required=${String(p.full_regression_signal.required_before_backlog_or_release_closure)} · execution_authorized=${String(p.full_regression_signal.execution_authorized)} · profile=${p.full_regression_signal.profile_id??(p.full_regression_signal as any).profile_authority??'current'} · budget 10-A=0`;updateButtons();}
  function alertLine(label:string,value:string,kind:'pass'|'block'):HTMLElement{const row=document.createElement('div');row.className=`story-test-plan-alert story-test-plan-alert--${kind}`;const strong=document.createElement('strong');strong.textContent=label;const span=document.createElement('span');span.textContent=value;row.append(strong,span);return row;}
  function testLine(testId:string,reason:string):HTMLElement{const li=document.createElement('li');const code=document.createElement('code');code.textContent=testId;const why=document.createElement('span');why.textContent=reason;li.append(code,why);return li;}
  async function requestRollbackApproval():Promise<void>{if(!execution||!isOwner)return;setState('loading','Solicitando approval separado de rollback…');try{const r=await client().storySourceChangeRollbackApprovalRequest(execution.execution_id);const id=String((r.data as any)?.approval?.approval_id??(r.data as any)?.approval_id??'');if(!id)throw new Error('La API no devolvió Approval ID de rollback.');rollbackInput.value=id;armApprovalCenterArtifactReviewHandoff(session,id);rollbackLink.href=`/approvals?handoff=artifact-review&approval_id=${encodeURIComponent(id)}`;rollbackLink.hidden=false;rollback.disabled=false;setState('pass',`PENDING · rollback approval ${id} creado; abre el Approval Center dirigido para decidir exactamente este ID.`);}catch(e){setState('block',errorText(e));}}
  async function executeRollback():Promise<void>{if(!execution||!isOwner)return;const id=rollbackInput.value.trim();if(!id){setState('block','BLOCK · ingresa Approval ID de rollback.');return;}setState('loading','Restaurando preimages exactos…');try{const r=await client().storySourceChangeRollback(execution.execution_id,id);evidence.textContent=JSON.stringify((r.data as any).rollback_evidence??r.data,null,2);await refresh({preserveNotice:true});setState('pass','PASS · rollback limpio; source_hash_parity=true.');}catch(e){setState('block',errorText(e));}}
  function persistApplyContext(activePlan:ChangePlan,approvalId:string):void{try{sessionStorage.setItem(APPLY_CONTEXT_SESSION_KEY,JSON.stringify({plan_id:activePlan.plan_id,plan_hash:activePlan.plan_hash,approval_id:approvalId,story_execution_id:String((activePlan as any).story_execution_id??'')}));}catch{/* UX pointer only; server remains authority. */}}
  function clearPersistedApplyContext():void{try{sessionStorage.removeItem(APPLY_CONTEXT_SESSION_KEY);}catch{/* UX pointer only. */}}
  async function restoreApplyContext(story:any):Promise<{restored:boolean;approvalUsable:boolean}>{
    const storyExecutionId=String(story?.execution_id??'').trim();
    const currentStatus=String(story?.status??'').toUpperCase();
    if(!storyExecutionId||!new Set(['IN_PROGRESS','CHANGES_READY']).has(currentStatus))return {restored:false,approvalUsable:false};
    const candidates:Array<any>=[];
    try{const raw=sessionStorage.getItem(APPLY_CONTEXT_SESSION_KEY);if(raw){const saved=JSON.parse(raw);if(saved?.plan_id)candidates.push({approval_id:String(saved.approval_id??''),subject:String(saved.plan_id),status:'saved',expired:false,updated_at:''});}}catch{clearPersistedApplyContext();}
    try{const listed=await client().listApprovals({limit:100});for(const row of (((listed.data as any)?.approvals??[]) as Array<any>)){if(String(row?.tool_id??'')==='story.source-change.apply'&&String(row?.action??'')==='filesystem.story_source_change_apply')candidates.push(row);}}catch{/* Approval Center is a recovery source, not a prerequisite for loading source tree. */}
    candidates.sort((a,b)=>String(b?.updated_at??b?.created_at??'').localeCompare(String(a?.updated_at??a?.created_at??'')));
    const seen=new Set<string>();
    for(const row of candidates){const planId=String(row?.subject??'').trim();if(!planId||seen.has(planId))continue;seen.add(planId);try{const got=await client().storySourceChangePlan(planId);const candidate=(got.data as any)?.plan as ChangePlan|undefined;if(!candidate||String((candidate as any).story_execution_id??'')!==storyExecutionId)continue;if(currentStatus==='CHANGES_READY'){const approved=String(row?.status??'').toLowerCase()==='approved';const boundHash=String(row?.metadata?.plan_hash??'');if(!approved||boundHash!==String(candidate.plan_hash??''))continue;plan=candidate;renderPlan();approvalInput.value='';approvalLink.hidden=true;clearPersistedApplyContext();updateButtons();return {restored:true,approvalUsable:false};}await client().storySourceChangePlanRecheck(candidate.plan_id,candidate.plan_hash);plan=candidate;renderPlan();const approvalId=String(row?.approval_id??'').trim();const usable=String(row?.status??'').toLowerCase()==='approved'&&row?.expired!==true&&Boolean(approvalId);if(usable){approvalInput.value=approvalId;armApprovalCenterArtifactReviewHandoff(session,approvalId);approvalLink.href=`/approvals?handoff=artifact-review&approval_id=${encodeURIComponent(approvalId)}`;approvalLink.hidden=false;persistApplyContext(candidate,approvalId);}else{approvalInput.value='';approvalLink.hidden=true;persistApplyContext(candidate,'');}updateButtons();return {restored:true,approvalUsable:usable};}catch{continue;}}
    return {restored:false,approvalUsable:false};
  }
  function clearPlan():void{plan=null;execution=null;clearStoryTestPlan();clearPersistedApplyContext();planMeta.textContent='';diff.textContent='Crea un SourceChangePlan para ver el diff completo.';impact.textContent='';approvalInput.value='';rollbackInput.value='';approvalLink.hidden=true;rollbackLink.hidden=true;updateButtons();}
  function renderPlan():void{if(!plan)return;planMeta.textContent=`${plan.plan_id} · hash ${plan.plan_hash.slice(0,16)} · risk=${plan.risk.level} · required=${plan.required_approval_role} · allowlist=${plan.exact_path_allowlist.join(', ')}`;diff.textContent=plan.full_diff||'(diff vacío)';impact.textContent=JSON.stringify(plan.test_impact_preview,null,2);updateButtons();}
  function renderDraft():void{if(!draft)return;draftInfo.dataset.conflict=draft.status==='CONFLICT'?'true':'false';draftInfo.textContent=`${draft.status} · ${draft.operation} → ${draft.target_path} · revision ${draft.revision_sha256.slice(0,12)} · source_mutations=false`;recheck.disabled=false;discard.disabled=false;updateButtons();}
  function updateButtons():void{save.disabled=!canAuthor;createPlan.disabled=!canAuthor||!draft||draft.status==='CONFLICT'||storyStatus!=='IN_PROGRESS';planRecheck.disabled=!canAuthor||!plan;dryRun.disabled=!canAuthor||!plan;requestApproval.disabled=!isOwner||!plan||storyStatus!=='IN_PROGRESS';apply.disabled=!isOwner||!plan||!approvalInput.value.trim()||storyStatus!=='IN_PROGRESS';validateStory.disabled=!canAuthor||!plan||storyStatus!=='CHANGES_READY';approveTestPlan.disabled=!isOwner||!storyTestPlan||storyTestPlan.status==='APPROVED';rejectTestPlan.disabled=!canAuthor||!storyTestPlan||storyTestPlan.status==='REJECTED';const waivable=storyTestPlan?.effective_required_tests?.some((testId)=>storyTestPlan?.test_policy?.[testId]?.waivable===true)??false;waiveTestPlan.disabled=!isOwner||!storyTestPlan||!waivable||!waiverReason.value.trim();requestRollback.disabled=!isOwner||!execution;rollback.disabled=!isOwner||!execution||!rollbackInput.value.trim();planValidationJobs.disabled=!canAuthor||!storyTestPlan||storyTestPlan.status!=='APPROVED';refreshValidationJobs.disabled=!storyTestPlan||storyTestPlan.status!=='APPROVED';}
  approvalInput.addEventListener('input',updateButtons); rollbackInput.addEventListener('input',updateButtons);
  function setState(kind:string,text:string):void{state.className=`notice notice--${kind}`;state.textContent=text;}
  return host;
}
function panel(title:string,description:string):HTMLElement{const p=document.createElement('section');p.className='panel';const h=document.createElement('h3');h.textContent=title;const d=document.createElement('p');d.textContent=description;p.append(h,d);return p;}
function button(label:string):HTMLButtonElement{const b=document.createElement('button');b.type='button';b.textContent=label;return b;}
function errorText(error:unknown):string{if(error instanceof DevPilotApiError){const payload=error.payload as any;const finding=payload?.findings?.[0]?.message;return `BLOCK · ${finding??error.message}`;}return error instanceof Error?`ERROR · ${error.message}`:'ERROR · fallo local no clasificado';}
