import { armApprovalCenterArtifactReviewHandoff, DevPilotApiClient, DevPilotApiError, writeQualityStoryContext } from '../api/client';
import type { AuthSessionContext, GovernedJobSnapshot } from '../api/types';
import { createWorkspaceGitOperationsPanel } from '../components/WorkspaceGitOperationsPanel';
import { renderOperationalSurfaceSummary } from '../components/OperationalPatterns';

type SourceRow = { source_id:string; relative_path:string; name:string; extension:string; size_bytes:number; language_hint:string };
type SourceData = { source_id:string; relative_path:string; content:string; sha256:string; language_hint:string };
type Draft = { draft_id:string; story_execution_id?:string; operation:'CREATE'|'EDIT'|'RENAME'; target_path:string; content?:string; status:'DRAFT'|'CONFLICT'; revision_sha256:string; source?:{source_id?:string;relative_path?:string;sha256?:string}; safety?:Record<string,unknown> };
type ChangePlan = { plan_id:string; plan_hash:string; full_diff:string; exact_path_allowlist:string[]; required_approval_role:string; risk:{level:string;reasons:string[]}; test_impact_preview:Record<string,unknown>; changes:Array<Record<string,unknown>> };
type Execution = { execution_id:string; status:string; plan_id:string; plan_hash:string; approval_id:string; changes:Array<Record<string,unknown>> };
type AgentProposal = { proposal_id:string; proposal_sha256:string; agent_type:'coding'|'test'; status:string; target_path:string; operation:'EDIT'|'CREATE'; proposed_content:string; full_diff:string; model_id:string; provider_id:string; access_route_id:string; agent_session:string; trace_id:string; tool_intent:Record<string,unknown>; tool_execution_decision:Record<string,unknown>; cost:Record<string,unknown>; provenance:Record<string,unknown>; safety:Record<string,unknown> };
type ImplementationProposalFile = { operation:'CREATE'; target_path:string; content:string; content_sha256:string; rationale:string; artifact_role?:string; docstring_summary?:string };
type ImplementationProposal = { proposal_id:string; proposal_sha256:string; story_id:string; story_title:string; status:string; technology:Record<string,string>; quality?:Record<string,unknown>; rationale:string[]; files:ImplementationProposalFile[]; provenance:Record<string,unknown>; safety:Record<string,unknown>; draft_ids:string[]; provider?:Record<string,unknown> };
type StoryActivationData = { story_activation?:any; story_execution_state?:any; dor_report?:any; context_pack?:any; implementation_route?:any; safety?:any };
type StoryTestPlan = { test_plan_id:string; test_plan_hash:string; status:string; story_execution_id:string; story_id:string; story_version?:string; source_change_plan_id:string; source_change_plan_hash:string; changed_paths:string[]; test_impact_report_hash:string; matched_contracts:Array<Record<string,unknown>>; matched_rules:Array<Record<string,unknown>>; required_tests:string[]; recommended_tests:string[]; effective_required_tests:string[]; test_reasons:Record<string,string[]>; test_policy:Record<string,{criticality:string;waivable:boolean;reason:string}>; unknown_impact:{paths:string[];manual_review_required:boolean;fail_closed:boolean}; sensitive_impact:{paths:string[];present:boolean;under_testing_blocked?:boolean}; full_regression_signal:{required_before_backlog_or_release_closure:boolean;informational_only:boolean;execution_authorized:boolean;profile_id?:string}; review?:Record<string,unknown>; active_waivers?:Array<Record<string,unknown>>; expired_waivers?:Array<Record<string,unknown>> };

const APPLY_CONTEXT_SESSION_KEY='devpilot.story-code.apply-context.v1';

export function renderStoryCodeWorkbenchView(tokenProvider:()=>string|null, session:AuthSessionContext):HTMLElement {
  const host=document.createElement('section'); host.className='story-code-workbench'; host.dataset.routeId='ui.story-code-workbench'; host.dataset.gsdlc09c='governed-source-change'; host.dataset.gsdlc09d='proposal-only-agent-assist'; host.dataset.gsdlc10a='story-test-plan'; host.dataset.gsdlc10b='story-validation-jobs'; host.dataset.gsdlc10d='story-git-governed'; host.dataset.gsdlc10e='story-cycle-e2e'; host.dataset.gsdlc13d01='story-activation-context-bridge'; host.dataset.gsdlc13d02='implementation-proposal-draft-set';
  const intro=panel('Story Code Workbench','Revisión y autoría sobre un árbol unificado de source/propuesta/drafts + asistencia proposal-only + SourceChangePlan gobernado + StoryTestPlan UI-native. Después de apply, Validar deriva Test Impact v2 y un plan de pruebas explicable; no ejecuta comandos ni Full Regression.');
  const safety=document.createElement('div'); safety.className='code-safety-strip'; safety.dataset.sourceWrite='approval-gated'; safety.textContent='SOURCE WRITE · APPROVAL-GATED · EXACT PATH ALLOWLIST · ATOMIC APPLY/ROLLBACK · SIN TERMINAL'; intro.append(safety); host.append(intro); host.append(renderOperationalSurfaceSummary({eyebrow:'Operación · Story/Code',title:'Cambio de código gobernado',state:'ready',stateDetail:'Prepara cambios, revisa diff y conserva apply/rollback approval-gated.',primaryAction:{label:'Crear o revisar SourceChangePlan',hierarchy:'primary',detail:'El source solo cambia tras approval owner y revalidación.'},gate:{label:'Quality gate',state:'PENDING',detail:'Se resuelve después del apply mediante Test Impact y jobs tipados.'},approval:{required:true,status:'antes de apply',role:'owner',effect:'Autoriza únicamente el plan/preimage exactos.'},diff:{risk:'server-derived',detail:'Diff, allowlist y Test Impact permanecen visibles antes de mutar.'},evidenceSummary:'Evidencia y diagnósticos',evidenceBody:'Plan hash · preimage · diff · Test Impact · approval ID · apply/rollback receipts. Guided reduce densidad; Expert conserva provenance completa.',recovery:'Rollback requiere approval separado; ninguna acción sensible se reanuda automáticamente.'}));
  const state=document.createElement('div'); state.className='notice'; state.setAttribute('role','status'); state.setAttribute('aria-live','polite'); host.append(state);
  const activationPanel=panel('Story activation & context','Puente gobernado desde Sprint FROZEN hacia StoryExecution. Preparar genera DoR + StoryContextPack runtime-only; Iniciar transiciona PLANNED → IN_PROGRESS. No escribe source ni modifica Planning.'); activationPanel.dataset.storyActivationPanel='true';
  const activationSummary=document.createElement('div'); activationSummary.className='code-draft-status'; activationSummary.dataset.storyActivationStatus='true';
  const candidateList=document.createElement('div'); candidateList.className='viewer-list'; candidateList.dataset.storyReadyCandidates='true';
  const activationActions=document.createElement('div'); activationActions.className='code-workbench-actions';
  const startStory=button('Iniciar story preparada'); startStory.dataset.startStoryExecution='true'; startStory.disabled=true;
  const refreshActivation=button('Actualizar activación'); refreshActivation.dataset.refreshStoryActivation='true';
  activationActions.append(startStory,refreshActivation);
  const reviewPanel=panel('Owner context review','Revisión humana previa al inicio. No es approval de source: confirma que Story, AC, DoR, requisitos, arquitectura, riesgos y test intent son coherentes. Si algo no cuadra, detén D01 y no inicies la Story.'); reviewPanel.dataset.storyContextReview='true';
  const reviewDecision=document.createElement('div'); reviewDecision.className='code-safety-strip'; reviewDecision.dataset.storyContextOwnerDecision='true'; reviewDecision.textContent='DECISIÓN OWNER · CONTINUAR = contexto suficiente → Iniciar story preparada · DETENER = inconsistencia o contexto insuficiente → no iniciar y reportar BLOCK.';
  const reviewStory=document.createElement('section'); reviewStory.className='viewer-card'; reviewStory.dataset.storyContextReviewStory='true';
  const reviewDor=document.createElement('section'); reviewDor.className='viewer-card'; reviewDor.dataset.storyContextReviewDor='true';
  const reviewFragments=document.createElement('div'); reviewFragments.className='viewer-list'; reviewFragments.dataset.storyContextReviewFragments='true';
  const reviewIdentity=document.createElement('section'); reviewIdentity.className='viewer-card'; reviewIdentity.dataset.storyContextReviewIdentity='true';
  const reviewRoute=document.createElement('section'); reviewRoute.className='viewer-card'; reviewRoute.dataset.storyContextReviewRoute='true';
  const rawDetails=document.createElement('details'); rawDetails.dataset.storyContextRawEvidence='true';
  const rawSummary=document.createElement('summary'); rawSummary.textContent='Evidencia técnica expandible · DoR / ContextPack / implementation route';
  const dorView=document.createElement('pre'); dorView.className='code-test-impact'; dorView.dataset.storyDorReport='true'; dorView.textContent='DoR pendiente.';
  const contextView=document.createElement('pre'); contextView.className='code-change-evidence'; contextView.dataset.storyContextPack='true'; contextView.textContent='StoryContextPack pendiente.';
  const routeView=document.createElement('pre'); routeView.className='code-change-evidence'; routeView.dataset.implementationRoute='true';
  rawDetails.append(rawSummary,dorView,contextView,routeView); reviewPanel.append(reviewDecision,reviewStory,reviewDor,reviewFragments,reviewIdentity,reviewRoute,rawDetails);
  activationPanel.append(activationSummary,candidateList,activationActions); host.append(activationPanel,reviewPanel);
  const layout=document.createElement('div'); layout.className='code-workbench-grid';
  const sourcePanel=panel('Source tree','Árbol unificado para source real, propuesta DevPilot y Draft Set runtime-only. Selecciona un archivo para revisarlo en el Editor de draft; la propuesta no escribe source.'); sourcePanel.dataset.storyImplementationProposal='integrated-source-tree';
  const sourcePolicyInfo=document.createElement('p'); sourcePolicyInfo.className='muted'; sourcePolicyInfo.dataset.sourcePolicyInfo='true';
  const implementationActions=document.createElement('div'); implementationActions.className='code-workbench-actions';
  const proposeImplementation=button('Proponer implementación desde contexto'); proposeImplementation.dataset.proposeImplementation='true';
  const acceptImplementation=button('Aceptar propuesta → Draft Set'); acceptImplementation.dataset.acceptImplementation='true'; acceptImplementation.disabled=true;
  const rejectImplementation=button('Rechazar propuesta'); rejectImplementation.dataset.rejectImplementation='true'; rejectImplementation.disabled=true;
  implementationActions.append(proposeImplementation,acceptImplementation,rejectImplementation);
  const implementationStatus=document.createElement('div'); implementationStatus.className='code-draft-status'; implementationStatus.dataset.implementationProposalStatus='true';
  const implementationDetails=document.createElement('details'); implementationDetails.dataset.implementationProposalEvidence='true';
  const implementationSummary=document.createElement('summary'); implementationSummary.textContent='Provenance, quality gate y safety de la propuesta';
  const implementationProvenance=document.createElement('pre'); implementationProvenance.className='code-change-evidence'; implementationProvenance.dataset.implementationProposalProvenance='true';
  implementationDetails.append(implementationSummary,implementationProvenance);
  const sourceList=document.createElement('div'); sourceList.className='code-source-list'; sourceList.dataset.sourceList='true'; sourcePanel.append(sourcePolicyInfo,implementationActions,implementationStatus,implementationDetails,sourceList);
  const editorPanel=panel('Editor de draft','Revisa aquí source, archivos virtuales de la propuesta o Draft Set. Los archivos PROPOSAL son read-only; después de ACCEPT pasan a Draft Set editable sin mutar source.');
  const sourceMeta=document.createElement('p'); sourceMeta.className='muted'; sourceMeta.dataset.sourceMeta='true'; sourceMeta.textContent='Selecciona un archivo o usa CREATE.';
  const mode=document.createElement('select'); mode.setAttribute('aria-label','Operación de draft'); for(const value of ['EDIT','CREATE','RENAME']){const o=document.createElement('option');o.value=value;o.textContent=value;mode.append(o);}
  const target=document.createElement('input'); target.type='text'; target.placeholder='ruta relativa al workspace'; target.setAttribute('aria-label','Ruta destino'); target.dataset.targetPath='true';
  const editor=document.createElement('textarea'); editor.rows=22; editor.spellcheck=false; editor.setAttribute('aria-label','Contenido del draft'); editor.dataset.draftEditor='true';
  const actions=document.createElement('div'); actions.className='code-workbench-actions';
  const save=button('Guardar draft'); save.dataset.saveDraft='true';
  const recheck=button('Revalidar preimage'); recheck.dataset.recheckDraft='true';
  const discard=button('Descartar draft'); discard.dataset.discardDraft='true';
  const sourceHash=document.createElement('code'); sourceHash.dataset.sourceHash='true';
  const draftInfo=document.createElement('div'); draftInfo.className='code-draft-status'; draftInfo.dataset.draftStatus='true';
  actions.append(save,recheck,discard); editorPanel.append(sourceMeta,mode,target,editor,actions,sourceHash,draftInfo);
  layout.append(sourcePanel,editorPanel); host.append(layout);

  const agentPanel=panel('Agent assistance · proposal-only','CodingAgent y TestAgent usan StoryContextPack + RAG + Model Gateway mock/local. Una propuesta nunca escribe source, no crea draft, no aprueba ni hace commit.'); agentPanel.dataset.agentAssistPanel='true';
  const agentControls=document.createElement('div'); agentControls.className='code-workbench-actions';
  const agentType=document.createElement('select'); agentType.setAttribute('aria-label','Tipo de agente'); agentType.dataset.agentType='true'; for(const [value,label] of [['coding','CodingAgent'],['test','TestAgent']]){const o=document.createElement('option');o.value=value;o.textContent=label;agentType.append(o);}
  const agentMode=document.createElement('select'); agentMode.setAttribute('aria-label','Ruta de modelo'); agentMode.dataset.agentMode='true'; for(const value of ['mock','fake-local']){const o=document.createElement('option');o.value=value;o.textContent=value;agentMode.append(o);}
  const agentInstruction=document.createElement('textarea'); agentInstruction.rows=3; agentInstruction.maxLength=2000; agentInstruction.placeholder='Describe la propuesta que deseas revisar. No incluyas secretos ni acciones destructivas.'; agentInstruction.setAttribute('aria-label','Instrucción para propuesta agentic'); agentInstruction.dataset.agentInstruction='true';
  const generateProposal=button('Generar propuesta'); generateProposal.dataset.generateAgentProposal='true';
  const acceptProposal=button('Aceptar en editor'); acceptProposal.dataset.acceptAgentProposal='true'; acceptProposal.disabled=true;
  const rejectProposal=button('Rechazar propuesta'); rejectProposal.dataset.rejectAgentProposal='true'; rejectProposal.disabled=true;
  agentControls.append(agentType,agentMode,generateProposal,acceptProposal,rejectProposal);
  const agentStatus=document.createElement('div'); agentStatus.className='code-draft-status'; agentStatus.dataset.agentProposalStatus='true';
  const agentDiff=document.createElement('pre'); agentDiff.className='code-full-diff'; agentDiff.dataset.agentProposalDiff='true'; agentDiff.textContent='Genera una propuesta para revisar su diff sin mutar draft/source.';
  const agentProvenance=document.createElement('pre'); agentProvenance.className='code-test-impact'; agentProvenance.dataset.agentProvenance='true';
  const agentSafety=document.createElement('pre'); agentSafety.className='code-change-evidence'; agentSafety.dataset.agentToolDecision='true';
  agentPanel.append(agentInstruction,agentControls,agentStatus,agentDiff,agentProvenance,agentSafety); host.append(agentPanel);

  const changePanel=panel('Governed source change','Secuencia obligatoria: immutable plan → diff/Test Impact → recheck/dry-run → owner approval → atomic apply → separate rollback approval.'); changePanel.dataset.changePlanPanel='true';
  const planActions=document.createElement('div'); planActions.className='code-workbench-actions';
  const createPlan=button('Crear SourceChangePlan'); createPlan.dataset.createChangePlan='true';
  const planRecheck=button('Revalidar plan'); planRecheck.dataset.recheckChangePlan='true';
  const dryRun=button('Dry-run'); dryRun.dataset.dryRunChangePlan='true';
  const requestApproval=button('Solicitar approval owner'); requestApproval.dataset.requestApplyApproval='true';
  const approvalLink=document.createElement('a'); approvalLink.href='/approvals'; approvalLink.target='_blank'; approvalLink.rel='noopener'; approvalLink.textContent='Abrir Approval Center dirigido ↗'; approvalLink.hidden=true;
  const approvalInput=document.createElement('input'); approvalInput.type='text'; approvalInput.placeholder='Approval ID aprobado'; approvalInput.setAttribute('aria-label','Approval ID de apply'); approvalInput.dataset.applyApprovalId='true';
  const apply=button('Aplicar plan aprobado'); apply.dataset.applyChangePlan='true';
  planActions.append(createPlan,planRecheck,dryRun,requestApproval,approvalLink,approvalInput,apply);
  const planMeta=document.createElement('div'); planMeta.className='code-draft-status'; planMeta.dataset.changePlanMeta='true';
  const diff=document.createElement('pre'); diff.className='code-full-diff'; diff.dataset.fullDiff='true'; diff.textContent='Crea un draft y luego el SourceChangePlan para ver el diff completo.';
  const impact=document.createElement('pre'); impact.className='code-test-impact'; impact.dataset.testImpact='true';
  changePanel.append(planActions,planMeta,diff,impact); host.append(changePanel);

  const validationPanel=panel('Validar · Test Impact y StoryTestPlan','Journey 10-A: Story CHANGES_READY → Validar → Test Impact v2 → review/approval. El plan explica required/recommended, escala unknown/sensitive y nunca ejecuta comandos ni Full Regression.'); validationPanel.dataset.storyTestPlanPanel='true';
  const validationActions=document.createElement('div'); validationActions.className='code-workbench-actions';
  const validateStory=button('Validar story'); validateStory.dataset.validateStory='true';
  const approveTestPlan=button('Aprobar StoryTestPlan'); approveTestPlan.dataset.approveStoryTestPlan='true';
  const rejectTestPlan=button('Rechazar StoryTestPlan'); rejectTestPlan.dataset.rejectStoryTestPlan='true';
  const waiverReason=document.createElement('input'); waiverReason.type='text'; waiverReason.maxLength=500; waiverReason.placeholder='Razón obligatoria para waiver owner'; waiverReason.setAttribute('aria-label','Razón de waiver del StoryTestPlan'); waiverReason.dataset.testPlanWaiverReason='true';
  const waiveTestPlan=button('Waiver owner'); waiveTestPlan.dataset.waiveStoryTestPlan='true';
  validationActions.append(validateStory,approveTestPlan,rejectTestPlan,waiverReason,waiveTestPlan);
  const testPlanMeta=document.createElement('div'); testPlanMeta.className='code-draft-status'; testPlanMeta.dataset.storyTestPlanMeta='true'; testPlanMeta.textContent='Aplica un SourceChangePlan y luego pulsa Validar.';
  const impactAlerts=document.createElement('div'); impactAlerts.className='story-test-plan-alerts'; impactAlerts.dataset.storyTestPlanAlerts='true';
  const testPlanGrid=document.createElement('div'); testPlanGrid.className='story-test-plan-grid';
  const requiredCard=document.createElement('section'); requiredCard.className='viewer-card'; const requiredTitle=document.createElement('h4'); requiredTitle.textContent='Required tests'; const requiredList=document.createElement('ul'); requiredList.className='story-test-plan-list'; requiredList.dataset.requiredTests='true'; requiredCard.append(requiredTitle,requiredList);
  const recommendedCard=document.createElement('section'); recommendedCard.className='viewer-card'; const recommendedTitle=document.createElement('h4'); recommendedTitle.textContent='Recommended tests'; const recommendedList=document.createElement('ul'); recommendedList.className='story-test-plan-list'; recommendedList.dataset.recommendedTests='true'; recommendedCard.append(recommendedTitle,recommendedList);
  testPlanGrid.append(requiredCard,recommendedCard);
  const fullSignal=document.createElement('div'); fullSignal.className='code-safety-strip'; fullSignal.dataset.fullRegressionSignal='true'; fullSignal.textContent='FULL REGRESSION · informative only · execution_authorized=false · budget 10-A=0';
  validationPanel.append(validationActions,testPlanMeta,impactAlerts,testPlanGrid,fullSignal); host.append(validationPanel);

  const jobsPanel=panel('Ejecutar validaciones · jobs gobernados','Journey 10-B: StoryTestPlan APPROVED → jobs tipados test/build/lint → Job Console con lifecycle, heartbeat y logs sanitizados. No acepta comandos libres ni inicia Full Regression.'); jobsPanel.dataset.storyValidationJobsPanel='true';
  const jobsActions=document.createElement('div'); jobsActions.className='code-workbench-actions';
  const planValidationJobs=button('Planificar jobs tipados'); planValidationJobs.dataset.planValidationJobs='true';
  const refreshValidationJobs=button('Actualizar jobs'); refreshValidationJobs.dataset.refreshValidationJobs='true';
  jobsActions.append(planValidationJobs,refreshValidationJobs);
  const jobsMeta=document.createElement('div'); jobsMeta.className='code-draft-status'; jobsMeta.dataset.storyValidationJobsMeta='true'; jobsMeta.textContent='Aprueba el StoryTestPlan para habilitar jobs test/build/lint allowlisted.';
  const jobsList=document.createElement('div'); jobsList.className='viewer-list story-validation-jobs'; jobsList.dataset.storyValidationJobsList='true';
  const jobsSafety=document.createElement('div'); jobsSafety.className='code-safety-strip'; jobsSafety.textContent='TYPED JOBS ONLY · NO ARBITRARY SHELL · BOUNDED LOGS · FULL REGRESSION=0 EN 10-B';
  jobsPanel.append(jobsActions,jobsMeta,jobsList,jobsSafety); host.append(jobsPanel);

  const rollbackPanel=panel('Apply manifest y rollback','Rollback es una operación gobernada separada; nunca reutiliza el approval de apply.'); rollbackPanel.dataset.rollbackPanel='true';
  const rollbackActions=document.createElement('div'); rollbackActions.className='code-workbench-actions';
  const requestRollback=button('Solicitar approval de rollback'); requestRollback.dataset.requestRollbackApproval='true';
  const rollbackLink=document.createElement('a'); rollbackLink.href='/approvals'; rollbackLink.target='_blank'; rollbackLink.rel='noopener'; rollbackLink.textContent='Abrir Approval Center ↗'; rollbackLink.hidden=true;
  const rollbackInput=document.createElement('input'); rollbackInput.type='text'; rollbackInput.placeholder='Approval ID de rollback aprobado'; rollbackInput.setAttribute('aria-label','Approval ID de rollback'); rollbackInput.dataset.rollbackApprovalId='true';
  const rollback=button('Ejecutar rollback aprobado'); rollback.dataset.executeRollback='true';
  const evidence=document.createElement('pre'); evidence.className='code-change-evidence'; evidence.dataset.changeEvidence='true';
  rollbackActions.append(requestRollback,rollbackLink,rollbackInput,rollback); rollbackPanel.append(rollbackActions,evidence); host.append(rollbackPanel);
  const storyGitPanel=createWorkspaceGitOperationsPanel({tokenProvider:()=>tokenProvider()??'',storyMode:true,onCommitComplete:async()=>{setState('pass','COMMIT PASS · Story DONE · trazabilidad Git completa; GSDLC-10-E puede continuar tras cierre Windows.');}}); host.append(storyGitPanel);

  const client=()=>new DevPilotApiClient({token:tokenProvider()});
  let selected:SourceData|null=null; let draft:Draft|null=null; let draftSet:Draft[]=[]; let sourceRowsCache:SourceRow[]=[]; let proposalReviewFile:ImplementationProposalFile|null=null; let plan:ChangePlan|null=null; let execution:Execution|null=null; let agentProposal:AgentProposal|null=null; let implementationProposal:ImplementationProposal|null=null; let storyTestPlan:StoryTestPlan|null=null; let validationJobs:GovernedJobSnapshot[]=[];
  let activation:StoryActivationData|null=null;
  let storyStatus='UNKNOWN'; let sourceRowsTotal=0; let sourcePolicy:Record<string,unknown>={};
  const canAuthor=session.principal.roles.some((x)=>['owner','developer'].includes(x)); const isOwner=session.principal.roles.includes('owner');
  save.disabled=!canAuthor; createPlan.disabled=true; planRecheck.disabled=true; dryRun.disabled=true; requestApproval.disabled=true; apply.disabled=true; requestRollback.disabled=true; rollback.disabled=true; validateStory.disabled=true; approveTestPlan.disabled=true; rejectTestPlan.disabled=true; waiveTestPlan.disabled=true; planValidationJobs.disabled=true; refreshValidationJobs.disabled=true;
  if(!canAuthor)save.title='Solo owner/developer puede persistir SourceDraftBuffer.'; if(!isOwner){requestApproval.title='Solo owner puede solicitar/aplicar.';apply.title=requestApproval.title;requestRollback.title=requestApproval.title;rollback.title=requestApproval.title;approveTestPlan.title='Solo owner puede aprobar StoryTestPlan.';waiveTestPlan.title='Solo owner puede crear waivers.';}

  mode.addEventListener('change',()=>{proposalReviewFile=null;mode.disabled=false;target.readOnly=false;editor.readOnly=false;const op=mode.value;if(op==='CREATE'){selected=null;target.value='';editor.value='';sourceMeta.textContent='CREATE manual · define una ruta permitida solo si deseas reemplazar/ajustar la propuesta DevPilot; la policy no decide arquitectura.';}else if(selected){target.value=selected.relative_path;editor.value=selected.content;sourceMeta.textContent=`${op} · ${selected.relative_path} · preimage ${selected.sha256.slice(0,12)}…`;}else{target.value='';editor.value='';sourceMeta.textContent=`${op} requiere seleccionar primero un source existente.`;}draft=null;clearPlan();renderDraftSet();updateButtons();});
  proposeImplementation.addEventListener('click',()=>void createImplementationProposal()); acceptImplementation.addEventListener('click',()=>void decideImplementationProposal('ACCEPT')); rejectImplementation.addEventListener('click',()=>void decideImplementationProposal('REJECT'));
  save.addEventListener('click',()=>void saveDraft()); recheck.addEventListener('click',()=>void recheckDraft()); discard.addEventListener('click',()=>void discardDraft());
  generateProposal.addEventListener('click',()=>void createAgentProposal()); acceptProposal.addEventListener('click',()=>void decideAgentProposal('ACCEPT')); rejectProposal.addEventListener('click',()=>void decideAgentProposal('REJECT'));
  agentType.addEventListener('change',()=>{if(agentType.value==='coding'&&!selected)agentStatus.textContent='CodingAgent requiere un source seleccionado; TestAgent puede proponer un archivo de test nuevo.';});
  createPlan.addEventListener('click',()=>void createChangePlan()); planRecheck.addEventListener('click',()=>void recheckPlan()); dryRun.addEventListener('click',()=>void runDryRun()); requestApproval.addEventListener('click',()=>void requestApplyApproval()); apply.addEventListener('click',()=>void executeApply()); validateStory.addEventListener('click',()=>void createStoryTestPlan()); approveTestPlan.addEventListener('click',()=>void decideStoryTestPlan('APPROVE')); rejectTestPlan.addEventListener('click',()=>void decideStoryTestPlan('REJECT')); waiveTestPlan.addEventListener('click',()=>void waiveStoryTestPlanRequest()); waiverReason.addEventListener('input',updateButtons); requestRollback.addEventListener('click',()=>void requestRollbackApproval()); rollback.addEventListener('click',()=>void executeRollback());
  planValidationJobs.addEventListener('click',()=>void createStoryValidationJobs()); refreshValidationJobs.addEventListener('click',()=>void loadStoryValidationJobs());
  startStory.addEventListener('click',()=>void startPreparedStory()); refreshActivation.addEventListener('click',()=>void refresh());
  void refresh();

  async function refresh(options:{preserveNotice?:boolean}={}):Promise<void>{
    const preserveNotice=options.preserveNotice===true;
    if(!preserveNotice)setState('loading','Cargando story/context y source tree…');
    try{
      const [activationResponse,status,sources,drafts]=await Promise.all([client().storyActivationStatus(),client().storyCodeStatus(),client().storyCodeSources(),client().storyCodeDrafts()]);
      activation=(activationResponse.data??{}) as StoryActivationData;
      renderActivation();
      const story=((status.data as any).story??activation?.story_execution_state??{});
      storyStatus=String(story.status??'UNKNOWN').toUpperCase();
      sourceMeta.textContent=`Story ${String(story.story_id??'sin story')} · ${storyStatus} · source write=approval-gated`;
      sourcePolicy=((status.data as any).source_policy??{}) as Record<string,unknown>;
      const sourceRows=((sources.data as any).sources??[]) as SourceRow[]; sourceRowsCache=sourceRows; sourceRowsTotal=sourceRows.length; renderSourcePolicy();
      draftSet=((drafts.data as any).drafts??[]) as Draft[]; renderImplementationProposal(); renderDraftSet();
      const restored=!plan ? await restoreApplyContext(story) : {restored:false,approvalUsable:false};
      updateButtons();
      if(!preserveNotice){
        if(restored.restored&&new Set(['CHANGES_READY','VALIDATING']).has(storyStatus))setState('pass',`PASS · SourceChangePlan restaurado para validación/remediación; Story ${storyStatus}.`);
        else if(restored.restored)setState('pass',restored.approvalUsable?'PASS · SourceChangePlan y approval owner restaurados desde autoridad server-side.':'PASS · SourceChangePlan restaurado desde autoridad server-side; solicite un approval owner nuevo antes de aplicar.');
        else setState('pass',`PASS · ${((sources.data as any).summary?.sources_total??0)} fuentes allowlisted.`);
      }
    }catch(e){
      setState('block',errorText(e));
      if(preserveNotice)throw e;
    }
  }
  function renderActivation():void{
    const data=activation??{}; const a=data.story_activation??{}; const current=data.story_execution_state??null;
    const candidates=Array.isArray(a.ready_candidates)?a.ready_candidates:[];
    activationSummary.textContent=`Sprint ${String(a.sprint_plan_id??'—')} · lifecycle=${String(a.sprint_lifecycle??'UNKNOWN')} · activation=${String(a.status??'UNKNOWN')} · current=${String(a.current_story_id??'none')} / ${String(a.current_story_status??'NONE')}`;
    candidateList.replaceChildren();
    if(candidates.length===0){const row=document.createElement('p');row.className='muted';row.textContent=current&&String(current.status)!=='DONE'?'StoryExecution activa; no se puede activar otra story hasta completar la actual.':'No hay Story READY elegible en el Sprint FROZEN.';candidateList.append(row);}else{
      for(const candidate of candidates){const row=document.createElement('section');row.className='viewer-list__item';row.dataset.readyStoryId=String(candidate.story_id??'');const title=document.createElement('strong');title.textContent=`${String(candidate.story_id??'')} · ${String(candidate.title??'')}`;const ac=document.createElement('p');ac.textContent=`READY · AC=${Array.isArray(candidate.acceptance_criteria)?candidate.acceptance_criteria.length:0} · order=${String(candidate.sprint_order??'')}`;const prepare=button('Preparar contexto');prepare.dataset.prepareStoryId=String(candidate.story_id??'');prepare.disabled=!canAuthor||Boolean(current&&String(current.status)!=='DONE');prepare.addEventListener('click',()=>void prepareStory(String(candidate.story_id??'')));row.append(title,ac,prepare);candidateList.append(row);}
    }
    startStory.disabled=!canAuthor||String(current?.status??'')!=='PLANNED'||!String(current?.state_sha256??'');
    const dor=data.dor_report??null; const cp=data.context_pack??null; const route=data.implementation_route??{};
    renderContextReview(current,dor,cp,route,data.safety??{});
    dorView.textContent=dor?JSON.stringify({status:dor.status,story_id:dor.story_id,dor_report_sha256:dor.dor_report_sha256,checks:dor.checks??dor.criteria??[]},null,2):'DoR pendiente.';
    contextView.textContent=cp?JSON.stringify({context_pack_id:cp.context_pack_id,context_sha256:cp.context_sha256,story:cp.story,fragments:cp.fragments,relevant_files:cp.relevant_files,safety:cp.safety},null,2):'StoryContextPack pendiente.';
    routeView.textContent=JSON.stringify(route,null,2);
  }
  function renderContextReview(current:any,dor:any,cp:any,route:any,safety:any):void{
    const story=cp?.story??{}; const fragments=Array.isArray(cp?.fragments)?cp.fragments:[]; const acceptance=fragments.find((x:any)=>String(x?.kind??'')==='acceptance');
    const executionStatus=String(current?.status??'NONE').toUpperCase();
    reviewDecision.textContent=executionStatus==='PLANNED'
      ? 'DECISIÓN OWNER · CONTINUAR = contexto suficiente → Iniciar story preparada · DETENER = inconsistencia o contexto insuficiente → no iniciar y reportar BLOCK.'
      : executionStatus==='IN_PROGRESS'
        ? 'DECISIÓN OWNER · CONTINUAR = contexto revisable/suficiente para cerrar D01 · DETENER = inconsistencia o contexto insuficiente → reportar BLOCK. Story ya IN_PROGRESS: no reiniciar ni iniciar D02 desde esta decisión.'
        : 'DECISIÓN OWNER · PENDIENTE · prepara una Story READY para materializar y revisar contexto antes de iniciarla.';
    reviewStory.replaceChildren();
    const storyTitle=document.createElement('h4'); storyTitle.textContent='1 · Story y Acceptance Criteria';
    const storyMeta=document.createElement('p'); storyMeta.textContent=story?.id?`${String(story.id)} · ${String(story.title??'')} · version=${String(story.version??'—')}`:'Prepara una Story READY para materializar el contexto.';
    const acList=document.createElement('ul'); acList.className='story-test-plan-list'; acList.dataset.storyAcceptanceCriteria='true';
    const criteria=String(acceptance?.content??'').split(/\r?\n/).map((x:string)=>x.trim()).filter(Boolean);
    for(const criterion of criteria){const li=document.createElement('li');li.textContent=criterion;acList.append(li);} if(!criteria.length){const li=document.createElement('li');li.textContent='Acceptance Criteria todavía no materializados.';acList.append(li);}
    reviewStory.append(storyTitle,storyMeta,acList);

    reviewDor.replaceChildren();
    const dorTitle=document.createElement('h4');dorTitle.textContent='2 · Definition of Ready';
    const dorMeta=document.createElement('p');dorMeta.textContent=dor?`DoR ${String(dor.status??'UNKNOWN')} · report=${String(dor.dor_report_sha256??'—').slice(0,16)}…`:'DoR pendiente.';
    const dorList=document.createElement('ul');dorList.className='story-test-plan-list';dorList.dataset.storyDorChecksReadable='true';
    const checks=Array.isArray(dor?.checks)?dor.checks:(Array.isArray(dor?.criteria)?dor.criteria:[]);
    for(const check of checks){const li=document.createElement('li');li.textContent=`${String(check?.status??'UNKNOWN')} · ${String(check?.code??check?.id??'check')} · ${String(check?.message??'')}`;dorList.append(li);} if(!checks.length){const li=document.createElement('li');li.textContent='Checks DoR todavía no disponibles.';dorList.append(li);}
    reviewDor.append(dorTitle,dorMeta,dorList);

    reviewFragments.replaceChildren();
    const labels:Record<string,string>={requirement:'3 · Requirement',adr:'4 · Architecture / ADR',risk:'5 · Risk / security','test-intent':'6 · Test intent'};
    for(const kind of ['requirement','adr','risk','test-intent']){const rows=fragments.filter((x:any)=>String(x?.kind??'')===kind);const card=document.createElement('section');card.className='viewer-list__item';card.dataset.contextKind=kind;const h=document.createElement('h4');h.textContent=labels[kind];card.append(h);if(!rows.length){const p=document.createElement('p');p.className='muted';p.textContent='No se materializó fragmento para esta categoría.';card.append(p);}for(const row of rows){const meta=document.createElement('p');meta.textContent=`${String(row?.target_id??'')} · source=${String(row?.source_ref??'')} · authority=${String(row?.authority_scope??'')}`;const content=document.createElement('pre');content.className='code-change-evidence';content.textContent=String(row?.content??'');card.append(meta,content);}reviewFragments.append(card);}

    reviewIdentity.replaceChildren();
    const identityTitle=document.createElement('h4');identityTitle.textContent='7 · ContextPack / StoryExecution / safety';
    const identityList=document.createElement('ul');identityList.className='story-test-plan-list';
    const identityRows=[`ContextPack: ${String(cp?.context_pack_id??'pending')}`,`Context hash: ${String(cp?.context_sha256??'pending')}`,`StoryExecution: ${String(current?.execution_id??'pending')} · ${String(current?.status??'NONE')}`,`State hash: ${String(current?.state_sha256??'pending')}`,`Planning mutated: ${String(safety?.planning_artifacts_mutated??false)}`,`Source mutated: ${String(safety?.source_mutations_performed??false)}`];
    for(const value of identityRows){const li=document.createElement('li');li.textContent=value;identityList.append(li);}reviewIdentity.append(identityTitle,identityList);

    reviewRoute.replaceChildren();
    const routeTitle=document.createElement('h4');routeTitle.textContent='8 · Implementation route / authority';
    const routeList=document.createElement('ul');routeList.className='story-test-plan-list';
    const manual=route?.manual??{};const assisted=route?.agent_assisted??{};const routeRows=[`Manual: ${manual?.available===true?'available':'unavailable'} · first-class=${String(manual?.first_class??false)} · source write=${String(manual?.source_write??'none')} · terminal required=${String(manual?.terminal_required??false)}`,`Agent-assisted: ${assisted?.available===true?'available':'unavailable'} · modes=${Array.isArray(assisted?.modes)?assisted.modes.join(', '):'none'} · proposal-only=${String(assisted?.proposal_only??false)}`,`Real local model required: ${String(route?.real_local_model_required??false)} · External API required: ${String(route?.external_api_required??false)}`,`Model route grants tool/apply/approval authority: ${String(route?.model_route_grants_tool_authority??false)} / ${String(route?.model_route_grants_apply_authority??false)} / ${String(route?.model_route_grants_approval_authority??false)}`];
    for(const value of routeRows){const li=document.createElement('li');li.textContent=value;routeList.append(li);}reviewRoute.append(routeTitle,routeList);
  }

  async function prepareStory(storyId:string):Promise<void>{
    if(!storyId){setState('block','BLOCK · Story ID READY ausente.');return;} setState('loading',`Preparando DoR + StoryContextPack para ${storyId}…`);
    try{const r=await client().storyActivationPrepare(storyId);activation=(r.data??{}) as StoryActivationData;renderActivation();const current=activation.story_execution_state??{};storyStatus=String(current.status??'UNKNOWN').toUpperCase();sourceMeta.textContent=`Story ${String(current.story_id??storyId)} · ${storyStatus} · source write=approval-gated`;updateButtons();setState('pass',`PASS · ${storyId} preparada en PLANNED; revisa DoR/contexto y luego pulsa Iniciar story preparada.`);}catch(e){setState('block',errorText(e));}
  }
  async function startPreparedStory():Promise<void>{
    const current=activation?.story_execution_state??{};const hash=String(current.state_sha256??'');if(!hash){setState('block','BLOCK · state_sha256 PLANNED ausente.');return;}setState('loading',`Iniciando ${String(current.story_id??'story')}…`);
    try{const r=await client().storyActivationStart(hash);activation=(r.data??{}) as StoryActivationData;renderActivation();await refresh({preserveNotice:true});const active=activation?.story_execution_state??{};storyStatus=String(active.status??'UNKNOWN').toUpperCase();setState('pass',`PASS · Story ${String(active.story_id??'')} ${storyStatus}; ya puedes elegir ruta Manual o proposal-only.`);}catch(e){setState('block',errorText(e));}
  }
  function renderSourcePolicy():void{const allowed=Array.isArray((sourcePolicy as any).allowed_extensions)?(sourcePolicy as any).allowed_extensions:[];sourcePolicyInfo.textContent=allowed.length?`Formatos permitidos por policy: ${allowed.join(', ')}. La policy solo limita formatos; el árbol de propuesta debe justificar ruta, responsabilidad y contenido desde Architecture/Story.`:'Policy de extensiones pendiente.';}
  function renderUnifiedSourceTree():void{
    sourceList.replaceChildren();
    type TreeEntry={path:string;state:'SOURCE'|'PROPOSAL'|'DRAFT'|'CONFLICT';detail:string;open:()=>void};
    const byPath=new Map<string,TreeEntry>();
    for(const row of sourceRowsCache){byPath.set(row.relative_path,{path:row.relative_path,state:'SOURCE',detail:row.language_hint,open:()=>void openSource(row)});}
    if(implementationProposal?.status==='PROPOSED'){
      for(const row of implementationProposal.files){if(!byPath.has(row.target_path))byPath.set(row.target_path,{path:row.target_path,state:'PROPOSAL',detail:`${row.artifact_role??'artifact'} · ${row.docstring_summary??'review required'}`,open:()=>openProposalFile(row)});}
    }
    for(const row of draftSet){if(!byPath.has(row.target_path)||row.status==='CONFLICT')byPath.set(row.target_path,{path:row.target_path,state:row.status==='CONFLICT'?'CONFLICT':'DRAFT',detail:`${row.operation} · runtime-only`,open:()=>selectDraft(row)});else if(row.status==='DRAFT')byPath.set(row.target_path,{path:row.target_path,state:'DRAFT',detail:`${row.operation} · runtime-only`,open:()=>selectDraft(row)});}
    if(!byPath.size){const p=document.createElement('p');p.className='muted';p.textContent=storyStatus==='IN_PROGRESS'?'Source tree vacío. Usa «Proponer implementación desde contexto» para que DevPilot derive un árbol virtual reviewable desde StoryContextPack + Architecture; Manual CREATE queda como override.':'No hay source allowlisted. Activa primero una Story READY antes de autoría.';sourceList.append(p);return;}
    const root=new Map<string,any>();
    for(const entry of [...byPath.values()].sort((a,b)=>a.path.localeCompare(b.path))){let node=root;const parts=entry.path.split('/').filter(Boolean);parts.forEach((part,index)=>{if(index===parts.length-1){node.set(part,entry);return;}let child=node.get(part);if(!(child instanceof Map)){child=new Map<string,any>();node.set(part,child);}node=child;});}
    const renderNode=(node:Map<string,any>,container:HTMLElement):void=>{for(const [name,value] of [...node.entries()].sort(([a],[b])=>a.localeCompare(b))){if(value instanceof Map){const details=document.createElement('details');details.open=true;details.className='code-source-tree-dir';const summary=document.createElement('summary');summary.textContent=`📁 ${name}`;const children=document.createElement('div');children.className='code-source-tree-children';details.append(summary,children);container.append(details);renderNode(value,children);}else{const entry=value as TreeEntry;const b=button(`${entry.state} · ${name}`);b.className='code-source-item';b.dataset.sourcePath=entry.path;b.dataset.sourceState=entry.state;b.title=`${entry.path} · ${entry.detail}`;b.addEventListener('click',entry.open);container.append(b);}}};
    renderNode(root,sourceList);
  }
  async function openSource(row:SourceRow):Promise<void>{setState('loading',`Leyendo ${row.relative_path}…`);try{const r=await client().storyCodeSource(row.source_id);selected=(r.data as any).source as SourceData;proposalReviewFile=null;mode.disabled=false;target.readOnly=false;editor.readOnly=false;mode.value='EDIT';target.value=selected.relative_path;editor.value=selected.content;sourceMeta.textContent=`SOURCE · ${selected.relative_path} · ${selected.language_hint}`;sourceHash.textContent=`preimage ${selected.sha256}`;draft=null;clearPlan();draftInfo.textContent='';recheck.disabled=true;discard.disabled=true;updateButtons();setState('pass','PASS · source leído por opaque id.');}catch(e){setState('block',errorText(e));}}
  function openProposalFile(row:ImplementationProposalFile):void{selected=null;draft=null;proposalReviewFile=row;mode.value='CREATE';mode.disabled=true;target.value=row.target_path;target.readOnly=true;editor.value=row.content;editor.readOnly=true;sourceMeta.textContent=`PROPOSAL · ${row.artifact_role??'artifact'} · ${row.target_path} · read-only hasta ACCEPT`;sourceHash.textContent=`proposal sha ${row.content_sha256}`;draftInfo.textContent=`Proposal-only · ${row.rationale} · docstring=${row.docstring_summary??'n/a'} · source_mutations=false`;clearPlan();updateButtons();setState('pass','REVIEW · archivo virtual de propuesta abierto en el Editor de draft; ACCEPT materializa el conjunto completo como Draft Set.');}
  async function createImplementationProposal():Promise<void>{setState('loading','Derivando implementation bundle v2 desde StoryContextPack + Architecture FROZEN…');try{const r=await client().storyImplementationProposalCreate();implementationProposal=(r.data as any).proposal as ImplementationProposal;renderImplementationProposal();if(implementationProposal.files.length)openProposalFile(implementationProposal.files[0]);setState('pass','PASS · propuesta v2 creada; revisa el árbol virtual archivo por archivo en el Editor de draft antes de ACCEPT. source/draft mutations=false.');}catch(e){implementationProposal=null;renderImplementationProposal();setState('block',errorText(e));}}
  async function decideImplementationProposal(decision:'ACCEPT'|'REJECT'):Promise<void>{if(!implementationProposal)return;setState('loading',decision==='ACCEPT'?'Materializando Draft Set runtime-only…':'Rechazando propuesta sin mutaciones…');try{const r=await client().storyImplementationProposalDecision(implementationProposal.proposal_id,implementationProposal.proposal_sha256,decision);implementationProposal=(r.data as any).proposal as ImplementationProposal;proposalReviewFile=null;mode.disabled=false;target.readOnly=false;editor.readOnly=false;if(decision==='ACCEPT'){draftSet=((r.data as any).drafts??[]) as Draft[];renderImplementationProposal();renderDraftSet();if(draftSet.length)selectDraft(draftSet[0]);setState('pass',`PASS · ${draftSet.length} SourceDraftBuffer materializados; source real permanece sin cambios.`);}else{renderImplementationProposal();renderDraftSet();setState('pass','PASS · propuesta rechazada; source/draft write=false.');}updateButtons();}catch(e){setState('block',errorText(e));}}
  function renderImplementationProposal():void{if(!implementationProposal){implementationStatus.textContent=sourceRowsTotal===0&&storyStatus==='IN_PROGRESS'?'Sin propuesta activa. DevPilot puede derivar un árbol virtual desde contexto/Architecture; Manual sigue disponible como override.':'La propuesta bootstrap solo aplica a Story IN_PROGRESS con source tree vacío.';implementationProvenance.textContent='';acceptImplementation.disabled=true;rejectImplementation.disabled=true;renderUnifiedSourceTree();return;}const provider=implementationProposal.provider??{};const quality=implementationProposal.quality??{};implementationStatus.textContent=`${implementationProposal.status} · ${implementationProposal.proposal_id} · ${String(provider.provider_id??'devpilot-local')} / ${String(provider.model_id??'unknown')} · profile=${String((implementationProposal.technology as any)?.profile_id??'unknown')} · files=${implementationProposal.files.length} · quality=${String((quality as any).ready_for_draft_materialization??'unknown')}`;implementationProvenance.textContent=JSON.stringify({rationale:implementationProposal.rationale,technology:implementationProposal.technology,quality:implementationProposal.quality,provenance:implementationProposal.provenance,safety:implementationProposal.safety},null,2);const pending=implementationProposal.status==='PROPOSED';acceptImplementation.disabled=!pending||((quality as any).ready_for_draft_materialization!==true);rejectImplementation.disabled=!pending;renderUnifiedSourceTree();}
  function renderDraftSet():void{renderUnifiedSourceTree();}
  function selectDraft(row:Draft):void{proposalReviewFile=null;mode.disabled=false;target.readOnly=false;editor.readOnly=false;draft=row;mode.value=row.operation;target.value=row.target_path;editor.value=String(row.content??'');sourceHash.textContent=row.source?.sha256?`preimage ${row.source.sha256}`:'preimage CREATE · target must remain absent';if(row.operation==='CREATE'){selected=null;sourceMeta.textContent=`DRAFT · CREATE · ${row.target_path} · runtime-only`;}renderDraft();clearPlan();updateButtons();}
  async function refreshDraftSet():Promise<void>{try{const r=await client().storyCodeDrafts();draftSet=((r.data as any).drafts??[]) as Draft[];renderDraftSet();}catch(e){setState('block',errorText(e));}}

  async function createAgentProposal():Promise<void>{
    if(!canAuthor){setState('block','BLOCK · owner/developer requerido para solicitar propuestas.');return;}
    const kind=agentType.value as 'coding'|'test';
    if(kind==='coding'&&!selected){setState('block','BLOCK · CodingAgent requiere source seleccionado.');return;}
    const instruction=agentInstruction.value.trim(); if(!instruction){setState('block','BLOCK · escribe una instrucción acotada.');return;}
    setState('loading',`Solicitando ${kind==='coding'?'CodingAgent':'TestAgent'} proposal-only por ${agentMode.value}…`);
    try{const r=await client().storyAgentProposalCreate({agent_type:kind,mode:agentMode.value as 'mock'|'fake-local',instruction,source_id:kind==='coding'?(selected?.source_id??null):null});agentProposal=(r.data as any).proposal as AgentProposal;renderAgentProposal();setState('pass','PASS · propuesta agentic creada; source/draft mutations=false.');}
    catch(e){agentProposal=null;renderAgentProposal();setState('block',errorText(e));}
  }
  async function decideAgentProposal(decision:'ACCEPT'|'REJECT'):Promise<void>{
    if(!agentProposal)return; setState('loading',`${decision==='ACCEPT'?'Aceptando para revisión humana en editor':'Rechazando'} propuesta…`);
    try{const r=await client().storyAgentProposalDecision(agentProposal.proposal_id,agentProposal.proposal_sha256,decision);agentProposal=(r.data as any).proposal as AgentProposal;
      if(decision==='ACCEPT'){const proposal=agentProposal; editor.value=proposal.proposed_content; target.value=proposal.target_path; if(proposal.operation==='CREATE'){mode.value='CREATE'; selected=null;} else {mode.value='EDIT';} draft=null; clearPlan(); draftInfo.textContent='Proposal ACCEPTED → contenido insertado en editor solamente; presiona Guardar draft para persistir SourceDraftBuffer.'; setState('pass','PASS · aceptación humana insertó contenido en editor; source/draft write=false.');}
      else {setState('pass','PASS · propuesta rechazada; source/draft write=false.');}
      renderAgentProposal(); updateButtons();
    }catch(e){setState('block',errorText(e));}
  }
  function renderAgentProposal():void{
    if(!agentProposal){agentStatus.textContent='';agentDiff.textContent='Genera una propuesta para revisar su diff sin mutar draft/source.';agentProvenance.textContent='';agentSafety.textContent='';acceptProposal.disabled=true;rejectProposal.disabled=true;return;}
    agentStatus.textContent=`${agentProposal.agent_type==='coding'?'CodingAgent':'TestAgent'} · ${agentProposal.status} · ${agentProposal.proposal_id} · target=${agentProposal.target_path}`;
    agentDiff.textContent=agentProposal.full_diff||'(diff vacío)';
    agentProvenance.textContent=JSON.stringify({model_id:agentProposal.model_id,provider_id:agentProposal.provider_id,access_route_id:agentProposal.access_route_id,agent_session:agentProposal.agent_session,trace_id:agentProposal.trace_id,cost:agentProposal.cost,provenance:agentProposal.provenance},null,2);
    agentSafety.textContent=JSON.stringify({ToolIntent:agentProposal.tool_intent,ToolExecutionDecision:agentProposal.tool_execution_decision,safety:agentProposal.safety},null,2);
    const pending=agentProposal.status==='PROPOSED';acceptProposal.disabled=!pending;rejectProposal.disabled=!pending;
  }
  async function saveDraft():Promise<void>{if(!canAuthor){setState('block','BLOCK · rol read-only.');return;}const operation=mode.value as 'CREATE'|'EDIT'|'RENAME';if(operation!=='CREATE'&&!selected){setState('block','BLOCK · selecciona source para EDIT/RENAME.');return;}if(!target.value.trim()){setState('block','BLOCK · define una ruta destino o acepta la propuesta DevPilot.');return;}setState('loading','Guardando SourceDraftBuffer runtime-only…');try{const r=await client().storyCodeDraftSave({operation,content:editor.value,target_path:target.value,source_id:selected?.source_id??null,expected_source_sha256:selected?.sha256??null,expected_revision_sha256:draft?.revision_sha256??null});draft=(r.data as any).draft as Draft;clearPlan();renderDraft();await refreshDraftSet();setState('pass','PASS · draft guardado; source real permanece sin cambios.');}catch(e){setState('block',errorText(e));}}
  async function recheckDraft():Promise<void>{if(!draft)return;setState('loading','Revalidando source preimage…');try{const r=await client().storyCodeDraftRecheck(draft.draft_id);draft=(r.data as any).draft as Draft;renderDraft();setState('pass','PASS · preimage vigente.');}catch(e){setState('block',errorText(e));draftInfo.textContent='CONFLICT · external edit/revalidation requerida';draftInfo.dataset.conflict='true';clearPlan();}}
  async function discardDraft():Promise<void>{if(!draft)return;try{await client().storyCodeDraftDiscard(draft.draft_id,draft.revision_sha256);draft=null;clearPlan();draftInfo.textContent='Draft descartado; source no fue modificado.';recheck.disabled=true;discard.disabled=true;await refreshDraftSet();updateButtons();setState('pass','PASS · runtime draft descartado.');}catch(e){setState('block',errorText(e));}}
  async function createChangePlan():Promise<void>{const usable=draftSet.filter((x)=>x.status!=='CONFLICT');if(!usable.length)return;setState('loading',`Construyendo plan inmutable para ${usable.length} draft(s) + Test Impact preview…`);try{const r=await client().storySourceChangePlanCreate(usable.map((x)=>x.draft_id));plan=(r.data as any).plan as ChangePlan;renderPlan();setState('pass',`PASS · SourceChangePlan inmutable creado con ${usable.length} draft(s); no hubo source write.`);}catch(e){setState('block',errorText(e));}}
  async function recheckPlan():Promise<void>{if(!plan)return;setState('loading','Revalidando preimages exactos…');try{await client().storySourceChangePlanRecheck(plan.plan_id,plan.plan_hash);setState('pass','PASS · plan/preimages vigentes.');}catch(e){setState('block',errorText(e));}}
  async function runDryRun():Promise<void>{if(!plan)return;setState('loading','Ejecutando dry-run gobernado…');try{const r=await client().storySourceChangeDryRun(plan.plan_id,plan.plan_hash);evidence.textContent=JSON.stringify(r.data,null,2);setState('pass','PASS · dry-run sin mutación de source.');}catch(e){setState('block',errorText(e));}}
  async function requestApplyApproval():Promise<void>{if(!plan||!isOwner)return;setState('loading','Solicitando approval owner exacto…');try{const r=await client().storySourceChangeApplyApprovalRequest(plan.plan_id,plan.plan_hash);const id=String((r.data as any)?.approval?.approval_id??(r.data as any)?.approval_id??'');if(!id)throw new Error('La API no devolvió Approval ID.');approvalInput.value=id;armApprovalCenterArtifactReviewHandoff(session,id);approvalLink.href=`/approvals?handoff=artifact-review&approval_id=${encodeURIComponent(id)}`;approvalLink.hidden=false;persistApplyContext(plan,id);apply.disabled=false;setState('pass',`PENDING · approval ${id} creado; abre el Approval Center dirigido y decide exactamente este ID con sesión humana owner.`);}catch(e){setState('block',errorText(e));}}
  async function executeApply():Promise<void>{if(!plan||!isOwner)return;const id=approvalInput.value.trim();if(!id){setState('block','BLOCK · ingresa el Approval ID aprobado.');return;}setState('loading','Revalidando preimage y ejecutando apply all-or-nothing…');try{const r=await client().storySourceChangeApply(plan.plan_id,plan.plan_hash,id);execution=(r.data as any).execution as Execution;evidence.textContent=JSON.stringify((r.data as any).apply_manifest??r.data,null,2);requestRollback.disabled=false;clearPersistedApplyContext();updateButtons();await refresh({preserveNotice:true});setState('pass','PASS · apply exacto verificado; manifest disponible.');}catch(e){setState('block',errorText(e));}}
  async function createStoryTestPlan():Promise<void>{if(!plan||!new Set(['CHANGES_READY','VALIDATING']).has(storyStatus)){setState('block',`BLOCK · Validar requiere SourceChangePlan restaurado y Story CHANGES_READY/VALIDATING; current=${storyStatus}.`);return;}setState('loading','Derivando Test Impact v2 y StoryTestPlan hash-bound…');try{const r=await client().storyTestPlanCreate(plan.plan_id,plan.plan_hash);storyTestPlan=(r.data as any).story_test_plan as StoryTestPlan;renderStoryTestPlan();setState('pass','PASS · StoryTestPlan derivado; required/recommended explicables; test execution=false.');}catch(e){setState('block',errorText(e));}}
  async function decideStoryTestPlan(decision:'APPROVE'|'REJECT'):Promise<void>{if(!storyTestPlan)return;if(decision==='APPROVE'&&!isOwner){setState('block','BLOCK · solo owner puede aprobar StoryTestPlan.');return;}if(decision==='REJECT'&&!canAuthor){setState('block','BLOCK · owner/developer requerido.');return;}setState('loading',`${decision==='APPROVE'?'Aprobando':'Rechazando'} StoryTestPlan por autoridad humana…`);try{const r=await client().storyTestPlanDecision(storyTestPlan.test_plan_id,{test_plan_hash:storyTestPlan.test_plan_hash,decision,reason:decision==='REJECT'?'Revisión humana rechazó el plan.':'Revisión humana owner aprobó el plan.'});storyTestPlan=(r.data as any).story_test_plan as StoryTestPlan;renderStoryTestPlan();if(decision==='APPROVE'){await refresh({preserveNotice:true});}setState('pass',`PASS · StoryTestPlan ${decision}${decision==='APPROVE'?' · Story VALIDATING':''}.`);}catch(e){setState('block',errorText(e));}}
  async function createStoryValidationJobs():Promise<void>{if(!storyTestPlan||storyTestPlan.status!=='APPROVED'){setState('block','BLOCK · StoryValidationJobs requieren StoryTestPlan APPROVED.');return;}setState('loading','Planificando jobs tipados desde StoryTestPlan aprobado…');try{const r=await client().createStoryValidationJobs(storyTestPlan.test_plan_id,storyTestPlan.test_plan_hash);validationJobs=((r.data as any)?.jobs??[]) as GovernedJobSnapshot[];writeQualityStoryContext({test_plan_id:storyTestPlan.test_plan_id,test_plan_hash:storyTestPlan.test_plan_hash,story_execution_id:storyTestPlan.story_execution_id,story_id:storyTestPlan.story_id});renderValidationJobs();setState('pass',`PASS · ${validationJobs.length} job(s) tipados planificados; contexto Quality 10-C preparado; Full=0.`);}catch(e){setState('block',errorText(e));}}
  async function loadStoryValidationJobs():Promise<void>{if(!storyTestPlan)return;try{const r=await client().listStoryValidationJobs(storyTestPlan.test_plan_id);validationJobs=((r.data as any)?.jobs??[]) as GovernedJobSnapshot[];renderValidationJobs();}catch(e){setState('block',errorText(e));}}
  async function startStoryValidationJob(job:GovernedJobSnapshot):Promise<void>{setState('loading',`Iniciando ${job.story_validation_kind??job.capability_id} como job tipado…`);try{await client().startStoryValidationJob(job.job_id);await loadStoryValidationJobs();setState('pass',`PASS · ${job.job_id} iniciado; observa lifecycle/logs en Job Console.`);}catch(e){setState('block',errorText(e));}}
  function renderValidationJobs():void{jobsList.replaceChildren();if(!validationJobs.length){jobsMeta.textContent='Sin jobs planificados para el StoryTestPlan actual.';updateButtons();return;}jobsMeta.textContent=`${validationJobs.length} job(s) · StoryTestPlan ${storyTestPlan?.test_plan_id??''} · lifecycle gobernado · Full=0`;for(const job of validationJobs){const row=document.createElement('div');row.className='viewer-list__item story-validation-job-row';const summary=document.createElement('span');summary.textContent=`${String(job.story_validation_status??job.status).toUpperCase()} · ${job.story_validation_kind??job.capability_id} · retry ${job.retry_count}/${job.retry_limit}`;const start=button('Iniciar');start.disabled=!['planned','approved','queued'].includes(job.status);start.addEventListener('click',()=>void startStoryValidationJob(job));const open=document.createElement('a');open.href=`/jobs/${encodeURIComponent(job.job_id)}`;open.textContent='Abrir Job Console';row.append(summary,start,open);jobsList.append(row);}updateButtons();}
  async function waiveStoryTestPlanRequest():Promise<void>{if(!storyTestPlan||!isOwner)return;const reason=waiverReason.value.trim();if(!reason){setState('block','BLOCK · waiver requiere razón explícita.');return;}const waived=storyTestPlan.effective_required_tests.filter((testId)=>storyTestPlan?.test_policy?.[testId]?.waivable===true);if(!waived.length){setState('block','BLOCK · no hay required tests waivable; sensitive/P0 permanecen obligatorios.');return;}setState('loading','Aplicando waiver owner con alcance y expiración…');try{const r=await client().storyTestPlanDecision(storyTestPlan.test_plan_id,{test_plan_hash:storyTestPlan.test_plan_hash,decision:'WAIVE',reason,waived_test_ids:waived,ttl_minutes:60});storyTestPlan=(r.data as any).story_test_plan as StoryTestPlan;waiverReason.value='';renderStoryTestPlan();setState('pass',`PASS · waiver owner aplicado a ${waived.length} test(s); expiry=60m.`);}catch(e){setState('block',errorText(e));}}
  function clearStoryTestPlan():void{storyTestPlan=null;validationJobs=[];jobsList.replaceChildren();jobsMeta.textContent='Aprueba el StoryTestPlan para habilitar jobs test/build/lint allowlisted.';testPlanMeta.textContent='Aplica un SourceChangePlan y luego pulsa Validar.';impactAlerts.replaceChildren();requiredList.replaceChildren();recommendedList.replaceChildren();fullSignal.textContent='FULL REGRESSION · informative only · execution_authorized=false · budget 10-A=0';waiverReason.value='';}
  function renderStoryTestPlan():void{if(!storyTestPlan){clearStoryTestPlan();updateButtons();return;}const p=storyTestPlan;testPlanMeta.textContent=`${p.test_plan_id} · hash ${p.test_plan_hash.slice(0,16)} · story=${p.story_id} · source-plan=${p.source_change_plan_id} · impact=${p.test_impact_report_hash.slice(0,16)} · status=${p.status}`;impactAlerts.replaceChildren();if(p.unknown_impact.paths.length){impactAlerts.append(alertLine('BLOCK/REVIEW · unknown impact',p.unknown_impact.paths.join(', '),'block'));}else{impactAlerts.append(alertLine('PASS · unknown impact','0 paths','pass'));}if(p.sensitive_impact.present){impactAlerts.append(alertLine('SENSITIVE · fail-closed',p.sensitive_impact.paths.join(', '),'block'));}else{impactAlerts.append(alertLine('PASS · sensitive impact','none','pass'));}requiredList.replaceChildren();for(const testId of p.required_tests){const reasons=(p.test_reasons?.[testId]??[]).join(' · ')||'Required by current Test Contract policy.';const policy=p.test_policy?.[testId];requiredList.append(testLine(testId,`${reasons} · ${policy?.criticality??'unknown'} · ${policy?.waivable?'waivable':'not waivable'}`));}if(!p.required_tests.length)requiredList.append(testLine('—','No required tests for this bounded delta.'));recommendedList.replaceChildren();for(const testId of p.recommended_tests){const reasons=(p.test_reasons?.[testId]??[]).join(' · ')||'Recommended by Test Impact v2.';recommendedList.append(testLine(testId,reasons));}if(!p.recommended_tests.length)recommendedList.append(testLine('—','No additional recommended tests.'));fullSignal.textContent=`FULL REGRESSION · informative only · required=${String(p.full_regression_signal.required_before_backlog_or_release_closure)} · execution_authorized=${String(p.full_regression_signal.execution_authorized)} · profile=${p.full_regression_signal.profile_id??(p.full_regression_signal as any).profile_authority??'current'} · budget 10-A=0`;updateButtons();}
  function alertLine(label:string,value:string,kind:'pass'|'block'):HTMLElement{const row=document.createElement('div');row.className=`story-test-plan-alert story-test-plan-alert--${kind}`;const strong=document.createElement('strong');strong.textContent=label;const span=document.createElement('span');span.textContent=value;row.append(strong,span);return row;}
  function testLine(testId:string,reason:string):HTMLElement{const li=document.createElement('li');const code=document.createElement('code');code.textContent=testId;const why=document.createElement('span');why.textContent=reason;li.append(code,why);return li;}
  async function requestRollbackApproval():Promise<void>{if(!execution||!isOwner)return;setState('loading','Solicitando approval separado de rollback…');try{const r=await client().storySourceChangeRollbackApprovalRequest(execution.execution_id);const id=String((r.data as any)?.approval?.approval_id??(r.data as any)?.approval_id??'');if(!id)throw new Error('La API no devolvió Approval ID de rollback.');rollbackInput.value=id;armApprovalCenterArtifactReviewHandoff(session,id);rollbackLink.href=`/approvals?handoff=artifact-review&approval_id=${encodeURIComponent(id)}`;rollbackLink.hidden=false;rollback.disabled=false;setState('pass',`PENDING · rollback approval ${id} creado; abre el Approval Center dirigido para decidir exactamente este ID.`);}catch(e){setState('block',errorText(e));}}
  async function executeRollback():Promise<void>{if(!execution||!isOwner)return;const id=rollbackInput.value.trim();if(!id){setState('block','BLOCK · ingresa Approval ID de rollback.');return;}setState('loading','Restaurando preimages exactos…');try{const r=await client().storySourceChangeRollback(execution.execution_id,id);evidence.textContent=JSON.stringify((r.data as any).rollback_evidence??r.data,null,2);await refresh({preserveNotice:true});setState('pass','PASS · rollback limpio; source_hash_parity=true.');}catch(e){setState('block',errorText(e));}}
  function persistApplyContext(activePlan:ChangePlan,approvalId:string):void{try{sessionStorage.setItem(APPLY_CONTEXT_SESSION_KEY,JSON.stringify({plan_id:activePlan.plan_id,plan_hash:activePlan.plan_hash,approval_id:approvalId,story_execution_id:String((activePlan as any).story_execution_id??'')}));}catch{/* UX pointer only; server remains authority. */}}
  function clearPersistedApplyContext():void{try{sessionStorage.removeItem(APPLY_CONTEXT_SESSION_KEY);}catch{/* UX pointer only. */}}
  async function restoreApplyContext(story:any):Promise<{restored:boolean;approvalUsable:boolean}>{
    const storyExecutionId=String(story?.execution_id??'').trim();
    const currentStatus=String(story?.status??'').toUpperCase();
    if(!storyExecutionId||!new Set(['IN_PROGRESS','CHANGES_READY','VALIDATING']).has(currentStatus))return {restored:false,approvalUsable:false};
    const candidates:Array<any>=[];
    try{const raw=sessionStorage.getItem(APPLY_CONTEXT_SESSION_KEY);if(raw){const saved=JSON.parse(raw);if(saved?.plan_id)candidates.push({approval_id:String(saved.approval_id??''),subject:String(saved.plan_id),status:'saved',expired:false,updated_at:''});}}catch{clearPersistedApplyContext();}
    try{const listed=await client().listApprovals({limit:100});for(const row of (((listed.data as any)?.approvals??[]) as Array<any>)){if(String(row?.tool_id??'')==='story.source-change.apply'&&String(row?.action??'')==='filesystem.story_source_change_apply')candidates.push(row);}}catch{/* Approval Center is a recovery source, not a prerequisite for loading source tree. */}
    candidates.sort((a,b)=>String(b?.updated_at??b?.created_at??'').localeCompare(String(a?.updated_at??a?.created_at??'')));
    const seen=new Set<string>();
    for(const row of candidates){const planId=String(row?.subject??'').trim();if(!planId||seen.has(planId))continue;seen.add(planId);try{const got=await client().storySourceChangePlan(planId);const candidate=(got.data as any)?.plan as ChangePlan|undefined;if(!candidate||String((candidate as any).story_execution_id??'')!==storyExecutionId)continue;if(new Set(['CHANGES_READY','VALIDATING']).has(currentStatus)){const approved=String(row?.status??'').toLowerCase()==='approved';const boundHash=String(row?.metadata?.plan_hash??'');if(!approved||boundHash!==String(candidate.plan_hash??''))continue;plan=candidate;renderPlan();approvalInput.value='';approvalLink.hidden=true;clearPersistedApplyContext();updateButtons();return {restored:true,approvalUsable:false};}await client().storySourceChangePlanRecheck(candidate.plan_id,candidate.plan_hash);plan=candidate;renderPlan();const approvalId=String(row?.approval_id??'').trim();const usable=String(row?.status??'').toLowerCase()==='approved'&&row?.expired!==true&&Boolean(approvalId);if(usable){approvalInput.value=approvalId;armApprovalCenterArtifactReviewHandoff(session,approvalId);approvalLink.href=`/approvals?handoff=artifact-review&approval_id=${encodeURIComponent(approvalId)}`;approvalLink.hidden=false;persistApplyContext(candidate,approvalId);}else{approvalInput.value='';approvalLink.hidden=true;persistApplyContext(candidate,'');}updateButtons();return {restored:true,approvalUsable:usable};}catch{continue;}}
    return {restored:false,approvalUsable:false};
  }
  function clearPlan():void{plan=null;execution=null;clearStoryTestPlan();clearPersistedApplyContext();planMeta.textContent='';diff.textContent='Crea un SourceChangePlan para ver el diff completo.';impact.textContent='';approvalInput.value='';rollbackInput.value='';approvalLink.hidden=true;rollbackLink.hidden=true;updateButtons();}
  function renderPlan():void{if(!plan)return;planMeta.textContent=`${plan.plan_id} · hash ${plan.plan_hash.slice(0,16)} · risk=${plan.risk.level} · required=${plan.required_approval_role} · allowlist=${plan.exact_path_allowlist.join(', ')}`;diff.textContent=plan.full_diff||'(diff vacío)';impact.textContent=JSON.stringify(plan.test_impact_preview,null,2);updateButtons();}
  function renderDraft():void{if(!draft)return;draftInfo.dataset.conflict=draft.status==='CONFLICT'?'true':'false';draftInfo.textContent=`${draft.status} · ${draft.operation} → ${draft.target_path} · revision ${draft.revision_sha256.slice(0,12)} · source_mutations=false`;recheck.disabled=false;discard.disabled=false;updateButtons();}
  function updateButtons():void{const sourceChangeAllowed=new Set(['IN_PROGRESS','VALIDATING']).has(storyStatus);save.disabled=!canAuthor||!sourceChangeAllowed||editor.readOnly;generateProposal.disabled=!canAuthor||!sourceChangeAllowed;proposeImplementation.disabled=!canAuthor||storyStatus!=='IN_PROGRESS'||sourceRowsTotal!==0||implementationProposal?.status==='PROPOSED';const validationAllowed=new Set(['CHANGES_READY','VALIDATING']).has(storyStatus);const usableDrafts=draftSet.filter((x)=>x.status!=='CONFLICT');createPlan.disabled=!canAuthor||usableDrafts.length===0||!sourceChangeAllowed;planRecheck.disabled=!canAuthor||!plan;dryRun.disabled=!canAuthor||!plan;requestApproval.disabled=!isOwner||!plan||!sourceChangeAllowed;apply.disabled=!isOwner||!plan||!approvalInput.value.trim()||!sourceChangeAllowed;validateStory.disabled=!canAuthor||!plan||!validationAllowed;approveTestPlan.disabled=!isOwner||!storyTestPlan||storyTestPlan.status==='APPROVED';rejectTestPlan.disabled=!canAuthor||!storyTestPlan||storyTestPlan.status==='REJECTED';const waivable=storyTestPlan?.effective_required_tests?.some((testId)=>storyTestPlan?.test_policy?.[testId]?.waivable===true)??false;waiveTestPlan.disabled=!isOwner||!storyTestPlan||!waivable||!waiverReason.value.trim();requestRollback.disabled=!isOwner||!execution;rollback.disabled=!isOwner||!execution||!rollbackInput.value.trim();planValidationJobs.disabled=!canAuthor||!storyTestPlan||storyTestPlan.status!=='APPROVED';refreshValidationJobs.disabled=!storyTestPlan||storyTestPlan.status!=='APPROVED';}
  approvalInput.addEventListener('input',updateButtons); rollbackInput.addEventListener('input',updateButtons);
  function setState(kind:string,text:string):void{state.className=`notice notice--${kind}`;state.textContent=text;}
  return host;
}
function panel(title:string,description:string):HTMLElement{const p=document.createElement('section');p.className='panel';const h=document.createElement('h3');h.textContent=title;const d=document.createElement('p');d.textContent=description;p.append(h,d);return p;}
function button(label:string):HTMLButtonElement{const b=document.createElement('button');b.type='button';b.textContent=label;return b;}
function errorText(error:unknown):string{if(error instanceof DevPilotApiError){const payload=error.payload as any;const finding=payload?.findings?.[0]?.message;return `BLOCK · ${finding??error.message}`;}return error instanceof Error?`ERROR · ${error.message}`:'ERROR · fallo local no clasificado';}
