// DevPilot UI route contract: ui.workspace-documents — GSDLC-04-E external edit reconciliation; read/reconcile only, never auto-revert.
import { DevPilotApiClient } from '../api/client';
import type { ArtifactReviewRecord } from '../api/types';
import { renderUiStateNotice } from './ContractBadges';

interface Options { tokenProvider: () => string; review: ArtifactReviewRecord; onReview: (review: ArtifactReviewRecord) => void; }

export function createArtifactReconciliationUX(options: Options): HTMLElement {
  const root=document.createElement('section'); root.className='artifact-reconciliation-ux'; root.dataset.gsdlc04e='artifact-reconciliation';
  let review=options.review; let busy=false; let message='Compruebe cambios externos después de editar, renombrar, borrar o cambiar de rama fuera de DevPilot.'; let blocked=false;
  const client=()=>new DevPilotApiClient({token:options.tokenProvider()});
  async function reconcile():Promise<void>{busy=true;blocked=false;message='Comparando source, provenance y Git sin revertir ni hacer merge…';draw();try{const r=await client().reconcileArtifactReview(review.review_id);const next=(r.data as any).review as ArtifactReviewRecord;if(!next)throw new Error('La API no devolvió el review reconciliado.');review=next;options.onReview(next);const rec=next.reconciliation;message=next.status==='REVALIDATION_REQUIRED'?`PASS · cambio externo ${String(rec?.change_kind||'detectado')} → REVALIDATION_REQUIRED; approval invalidado.`:'PASS · no hay drift externo; FROZEN permanece válido.';}catch(e){blocked=true;message=e instanceof Error?e.message:String(e);}finally{busy=false;draw();}}
  function draw(){root.replaceChildren();const h=document.createElement('h3');h.textContent='Reconciliación externa · VS Code / Git';root.append(h);const p=document.createElement('p');p.textContent='DevPilot detecta drift y muestra diff/provenance. Nunca revierte automáticamente cambios externos ni hace merge oculto.';root.append(p);const b=document.createElement('button');b.type='button';b.textContent=busy?'Reconciliando…':'Detectar cambio externo';b.disabled=busy||!['APPROVED','FROZEN','REVALIDATION_REQUIRED'].includes(review.status);b.addEventListener('click',()=>void reconcile());root.append(b);const st=document.createElement('div');st.className='artifact-reconciliation-status';st.setAttribute('role',blocked?'alert':'status');st.setAttribute('aria-live','polite');st.textContent=message;root.append(st);const rec=review.reconciliation;if(rec){const dl=document.createElement('dl');for(const [k,v] of [['Cambio',rec.change_kind||''],['Estado',review.status],['Approval válido',String(review.approval_valid)],['Ruta gobernada',rec.original_relative_path||review.relative_path],['Ruta detectada',rec.detected_relative_path||'—'],['Rama al freeze',rec.git_branch_at_freeze||'—'],['Rama actual',rec.git_branch_current||'—'],['Branch changed',String(Boolean(rec.branch_changed))],['Approved SHA',rec.previous_approved_sha256||review.approved_sha256||'—'],['Current SHA',rec.current_normalized_sha256||'—']]){const dt=document.createElement('dt');dt.textContent=k;const dd=document.createElement('dd');dd.textContent=String(v);dl.append(dt,dd);}root.append(dl);const prov=document.createElement('details');const ps=document.createElement('summary');ps.textContent='Source provenance';const pp=document.createElement('pre');pp.textContent=JSON.stringify(rec.source_provenance||{},null,2);prov.append(ps,pp);root.append(prov);const diff=document.createElement('details');diff.open=review.status==='REVALIDATION_REQUIRED';const ds=document.createElement('summary');ds.textContent='Git diff';const dp=document.createElement('pre');dp.className='artifact-reconciliation-diff';dp.textContent=rec.git_diff||'(sin diff textual disponible; rename/delete puede representarse por status/provenance)';diff.append(ds,dp);root.append(diff);if(review.status==='REVALIDATION_REQUIRED')root.append(renderUiStateNotice('block','Approval/FROZEN anterior invalidado. Cree un nuevo DRAFT y vuelva a validar; DevPilot no auto-revierte el cambio externo.'));}}
  draw();return root;
}
