// DevPilot UI contract: GSDLC-04-D governed artifact review/apply/freeze.
import { armApprovalCenterArtifactReviewHandoff, DevPilotApiClient } from '../api/client';
import type { ArtifactReviewRecord, AuthSessionContext } from '../api/types';
import { renderContractBadges, renderUiStateNotice } from './ContractBadges';

interface Options { tokenProvider: () => string; session: AuthSessionContext; onMutationComplete?: () => void | Promise<void>; }
type State = 'idle'|'loading'|'ready'|'block'|'applied'|'frozen';

export function createArtifactReviewFlow(options: Options): HTMLElement {
  const root=document.createElement('section'); root.className='panel artifact-review-flow'; root.dataset.gsdlc04d='artifact-review-flow';
  let importId=''; let documentId=''; let review:ArtifactReviewRecord|undefined; let approvalId=''; let executionId=''; let reason='Promover artefacto validado y revisado mediante apply gobernado.'; let state:State='idle'; let message='Seleccione o cree un DRAFT para iniciar validate → findings → diff → approval → apply → freeze.';
  const client=()=>new DevPilotApiClient({token:options.tokenProvider()});
  async function startReview(){if(!importId&&!documentId)return; state='loading';message='Ejecutando validadores por ArtifactProfile y construyendo plan/diff inmutable…';draw();try{const r=importId?await client().startArtifactImportReview(importId):await client().startArtifactDocumentReview(documentId);review=(r.data as any).review;state=review?.status==='APPROVAL_REQUIRED'?'ready':'block';message=state==='ready'?'PASS · validación limpia; plan/diff inmutable listo para approval.':'BLOCK · revise findings antes de continuar.';}catch(e){state='block';message=readable(e);}draw();}
  async function requestApproval(){const plan=review?.plan as any;if(!plan)return;state='loading';message='Solicitando approval exacto para el plan inmutable…';draw();try{const r=await client().requestWorkspaceEditApplyApproval(plan.plan_id,{plan_hash:plan.plan_hash,reason,ttl_minutes:15});const a=(r.data as any).approval;approvalId=String(a?.approval_id||'');if(!approvalId)throw new Error('La API no devolvió Approval ID.');armApprovalCenterArtifactReviewHandoff(options.session,approvalId);state='ready';message=`Approval solicitado: ${approvalId}. Abra Approval Center dirigido, decida y luego verifique.`;}catch(e){state='block';message=readable(e);}draw();}
  async function verifyApproval(){if(!approvalId)return;state='loading';draw();try{const r=await client().showApproval(approvalId);const a=(r.data as any).approval;if(String(a?.approval_id)!==approvalId)throw new Error('Approval ID mismatch.');if(a?.status!=='approved')throw new Error(`Approval ${approvalId} todavía está ${String(a?.status||'unknown')}.`);state='ready';message=`PASS · approval exacto ${approvalId} está approved.`;}catch(e){state='block';message=readable(e);}draw();}
  async function apply(){const plan=review?.plan as any;if(!plan||!approvalId)return;state='loading';message='Revalidando preimage/actor/session y ejecutando atomic apply…';draw();try{const r=await client().applyWorkspaceEdit(plan.plan_id,{plan_hash:plan.plan_hash,approval_id:approvalId});const exe=(r.data as any).execution;executionId=String(exe?.execution_id||'');if(!executionId)throw new Error('Apply no devolvió execution_id.');state='applied';message=`PASS · atomic apply verificado (${executionId}); falta freeze del hash aprobado.`;await options.onMutationComplete?.();}catch(e){state='block';message=readable(e);}draw();}
  async function freeze(){if(!review||!executionId)return;state='loading';message='Verificando exact apply + approval + hash antes de FROZEN…';draw();try{const r=await client().freezeArtifactReview(review.review_id,executionId);review=(r.data as any).review;state='frozen';message=`PASS · FROZEN en hash ${review?.approved_sha256||''}; transition evidence emitida.`;}catch(e){state='block';message=readable(e);}draw();}
  function openApproval(){if(!approvalId)return;armApprovalCenterArtifactReviewHandoff(options.session,approvalId);globalThis.open(`/approvals?handoff=artifact-review&approval_id=${encodeURIComponent(approvalId)}`,'_blank','noopener,noreferrer');}
  function draw(){root.replaceChildren();const h=document.createElement('div');h.className='artifact-editor-heading';const title=document.createElement('h2');title.textContent='Artifact Review · validate, approve, apply & freeze';h.append(title,renderContractBadges('ui.workspace-documents',{dryRunLabel:'PLAN → APPROVAL → APPLY',warning:'La UI nunca decide authority: sesión/RBAC/Policy/Approval permanecen server-side.'}));root.append(h);const intro=document.createElement('p');intro.textContent='Valida según ArtifactProfile, navega findings, muestra diff completo y solo permite source write mediante el motor atómico UOC-005 con approval exacto.';root.append(intro);
    const form=document.createElement('div');form.className='artifact-review-controls';const label=document.createElement('label');label.textContent=importId?'Import ID DRAFT':'Documento MANUAL seleccionado';const input=document.createElement('input');input.value=importId||documentId;input.placeholder=importId?'imp_…':'document_id';input.addEventListener('input',()=>{if(importId)importId=input.value.trim();else documentId=input.value.trim();review=undefined;approvalId='';executionId='';state='idle';});label.append(input);const reasonLabel=document.createElement('label');reasonLabel.textContent='Motivo de approval';const reasonInput=document.createElement('input');reasonInput.value=reason;reasonInput.addEventListener('input',()=>{reason=reasonInput.value;});reasonLabel.append(reasonInput);form.append(label,reasonLabel);root.append(form);
    const status=document.createElement('div');status.className='artifact-review-status';status.dataset.state=state;status.setAttribute('role',state==='block'?'alert':'status');status.setAttribute('aria-live','polite');status.textContent=message;root.append(status);
    const actions=document.createElement('div');actions.className='artifact-editor-actions';actions.append(btn('Validar DRAFT',()=>void startReview(),state==='loading'||(!importId&&!documentId)),btn('Solicitar approval',()=>void requestApproval(),state==='loading'||review?.status!=='APPROVAL_REQUIRED'||Boolean(approvalId)),btn('Abrir Approval Center ↗',openApproval,!approvalId),btn('Verificar approval',()=>void verifyApproval(),!approvalId||state==='loading'),btn('Aplicar cambio aprobado',()=>void apply(),!approvalId||!review||state==='loading'||Boolean(executionId)),btn('Freeze hash aprobado',()=>void freeze(),!executionId||state==='loading'||state==='frozen')) ;root.append(actions);
    if(review){root.append(renderReview(review));}if(state==='block')root.append(renderUiStateNotice('block','Flujo detenido fail-closed. No continúe hasta resolver findings/approval/preimage.'));}
  (root as HTMLElement & { setImport?: (id:string)=>void; setDocument?: (id:string)=>void }).setImport=(id:string)=>{importId=id;documentId='';review=undefined;approvalId='';executionId='';state='idle';message=`DRAFT ${id} recibido. Pulse Validar DRAFT.`;draw();};
  (root as HTMLElement & { setImport?: (id:string)=>void; setDocument?: (id:string)=>void }).setDocument=(id:string)=>{if(importId)return;documentId=id;review=undefined;approvalId='';executionId='';state='idle';message=id?`Documento ${id} seleccionado. Guarde un DRAFT MANUAL y pulse Validar DRAFT.`:'Seleccione o cree un DRAFT para iniciar validate → findings → diff → approval → apply → freeze.';draw();};
  draw();return root;
}
function renderReview(r:ArtifactReviewRecord):HTMLElement{const s=document.createElement('section');s.className='artifact-review-evidence';const h=document.createElement('h3');h.textContent=`Review ${r.review_id} · ${r.status}`;s.append(h);const meta=document.createElement('dl');for(const [k,v] of [['Artifact',String((r.artifact as any).artifact_id||'')],['Target',r.relative_path],['Profile',String((r.validation as any).profile_id||'')],['Plan hash',String((r.plan as any)?.plan_hash||'')],['Base hash',r.base_sha256],['Content hash',r.content_sha256]]){const dt=document.createElement('dt');dt.textContent=k;const dd=document.createElement('dd');dd.textContent=v;meta.append(dt,dd);}s.append(meta);if(r.findings?.length){const list=document.createElement('ul');list.className='artifact-review-findings';for(const f of r.findings){const li=document.createElement('li');const text=document.createElement('span');text.textContent=`${f.severity.toUpperCase()} · ${f.id}${f.line?` · línea ${f.line}`:''}${f.section?` · sección ${f.section}`:''}: ${f.message}`;li.append(text);if(f.line||f.section){const nav=btn('Ir al hallazgo',()=>globalThis.dispatchEvent(new CustomEvent('devpilot:artifact-finding-navigate',{detail:{relative_path:r.relative_path,line:f.line??null,section:f.section??null}})));nav.className='button-secondary';li.append(nav);}list.append(li);}s.append(list);}const diff=String((r.plan as any)?.diff?.content||'');if(diff){const pre=document.createElement('pre');pre.className='artifact-review-diff';pre.textContent=diff;s.append(pre);}return s;}
function btn(label:string,handler:()=>void,disabled=false):HTMLButtonElement{const b=document.createElement('button');b.type='button';b.textContent=label;b.disabled=disabled;b.addEventListener('click',handler);return b;}
function readable(e:unknown):string{return e instanceof Error?e.message:String(e);}
